const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes={tree:['Family tree','Explore the complete family inventory. Select a person to inspect their role, evidence state, and dossier references.'],people:['People','Every direct-line, collateral, sponsor, and research-lead entry in Appendix F.'],branches:['Branch dossiers','Read the documentary cores and branch-specific investigations in full.'],timeline:['Timeline','Dated person records and event leads, ordered chronologically. Dates and identities retain their source qualifications.'],evidence:['Evidence','The protocol, claim register, promotion rules, relationship dataset, and completeness gates.'],sources:['Sources','Canonical source register, legacy ID crosswalk, citations, and verified retrieval procedures.'],research:['Research Queue','Record acquisition, branch-specific proof sequences, and negative-search history.'],conflicts:['Conflicts','Rejected assertions, competing hypotheses, same-name quarantines, and unresolved identities.'],migration:['Migration','Geographic origins, migration evidence, and Irish-origin reconstruction.'],archive:['Archive','The complete public-edition dossier, including Appendices A–G and all nine lossless legacy annexes.']};
let data,route='tree',shown=[],sourceIndex=new Map();
const states=s=>['SUPPORTED','PROVISIONAL','UNRESOLVED','REJECTED','DERIVATIVE'].filter(x=>s.toUpperCase().includes(x));
const badges=s=>states(s).map(x=>`<span class="badge ${x.toLowerCase()}">${x}</span>`).join('');
function linked(t){return esc(t).replace(/\bC\d{3}\b/g,id=>sourceIndex.has(id)?`<a class="source-link" href="#sources/${sourceIndex.get(id)}">${id}</a>`:id).replace(/https?:\/\/[^\s<]+/g,url=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${url}</a>`)}
function block(b){return b.type==='p'?`<p>${linked(b.text)}</p>`:`<div class="table-wrap" tabindex="0" aria-label="Scrollable dossier table"><table><thead><tr>${(b.rows[0]||[]).map(c=>`<th scope="col">${linked(c)}</th>`).join('')}</tr></thead><tbody>${b.rows.slice(1).map(r=>`<tr>${r.map(c=>`<td>${linked(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function section(s,open=false){return `<details id="${s.id}" ${open?'open':''}><summary>${esc(s.title)}<small>${s.legacy?'LEGACY ANNEX · '+esc(s.annex||'Historical layer'):'PART I · CANONICAL SYNTHESIS'} · ${s.id}</small></summary><div class="document">${s.legacy?'<p class="legacy">Historical source layer. Retained claims may be superseded or rejected. Part I controls current interpretation; this annex does not promote evidence.</p>':''}${s.blocks.map(block).join('')}<a href="#archive/${s.id}">Link to this section ↗</a></div></details>`}
function card(p){return `<button class="card person-card" data-person="${p.id}"><span class="eyebrow">${esc(p.branch)}</span><h3>${esc(p.name)}</h3><p>${esc(p.dates)}</p>${badges(p.state)}<p>${esc(p.state)}</p><p>${esc(p.role)}</p></button>`}
function matches(t){return (!$('#search').value||t.toLowerCase().includes($('#search').value.toLowerCase()))&&(!$('#branch').value||t.toLowerCase().includes($('#branch').value.toLowerCase()))&&(!$('#state').value||t.toUpperCase().includes($('#state').value))}
function selectedSections(){const all=data.sections.filter(s=>!s.legacy),rules={branches:/^(?:[4-9]|10)\.|^(?:4|5|6|7|8|9|10)\.[1-9]/,evidence:/^(?:1\.|1\.[12]|3\.|16\.|19\.|19\.[12]|20\.|21\.|22\.|Appendix [DFG]|[DG]\.)/,sources:/^(?:14\.|15\.|Appendix [BE]|E\.)/,research:/^(?:13\.|13\.1|17\.|18\.|18\.[123]|Appendix E|E\.[123])/,conflicts:/^(?:5\.1|8\.|8\.1|12\.|Appendix D|D\.)/,migration:/^(?:11\.|7\.3)/};return (route==='archive'?data.sections:all.filter(s=>rules[route]?.test(s.title))).filter(s=>matches(JSON.stringify(s)))}
function pedigree(){const s=data.sections.find(s=>!s.legacy&&s.title.startsWith('3.'));const rows=s.blocks.find(b=>b.type==='table').rows.slice(1);return `<h2>Direct-line pathway</h2><p>Generations follow the canonical direct-line register. Each step retains its evidence qualification.</p><div class="pedigree" tabindex="0" aria-label="Scrollable direct-line family tree">${rows.map(r=>`<article class="generation"><span class="eyebrow">GENERATION ${esc(r[0])}</span><h3>${esc(r[1])}</h3><p>${esc(r[2])}</p>${badges(r[3])}<p>${esc(r[3])}</p><small>${esc(r[4])}</small><a class="action" href="#archive/${s.id}">View evidence ↗</a></article>`).join('')}</div>`}
function neighborhood(p){const s=data.sections.find(s=>!s.legacy&&s.title.startsWith('21.'));const rows=s.blocks.find(b=>b.type==='table').rows.slice(1);const aliases={'Edward Ellery DeVine / DeVeine':'Edward Ellery DeVine/DeVeine','Hazel Emma Berg Dennewitz':'Hazel Emma Berg'};const r=rows.find(r=>r[1]===(aliases[p.name]||p.name));if(!r)return `<p>${esc(p.role)}. Consult the linked branch dossier for relationship evidence.</p>`;return `<div class="kinship"><div><small>FATHER · source assertion</small><p>${esc(r[3])}</p></div><div><small>MOTHER · source assertion</small><p>${esc(r[4])}</p></div><div><small>PERSON</small><p>${esc(r[1])}</p></div><div><small>SPOUSE(S) · source assertion</small><p>${esc(r[5])}</p></div></div><p>${esc(r[6])}. These fields preserve the relationship dataset; they do not independently establish parentage.</p><a href="#archive/${s.id}" data-dismiss>Read the relationship dataset ↗</a>`}
function showPerson(id){const p=data.people.find(x=>x.id===id);if(!p)return;$('#person-content').innerHTML=`<p class="eyebrow">${esc(p.branch)} · APPENDIX F</p><h2>${esc(p.name)}</h2>${badges(p.state)}<dl><dt>Dates / lead</dt><dd>${esc(p.dates)}</dd><dt>Relationship / role</dt><dd>${esc(p.role)}</dd><dt>Canonical treatment</dt><dd>${esc(p.state)}</dd><dt>Privacy</dt><dd>${p.living?'Living-person birth details withheld in this public edition.':'Historical research record; uncertainties retained.'}</dd></dl><h3>Relationship context</h3>${neighborhood(p)}<h3>Dossier references</h3><div class="refs">${p.references.map(id=>{let s=data.sections.find(x=>x.id===id);return `<a href="#archive/${id}" data-dismiss>${esc(s.title)}</a>`}).join('')}</div>`;$('#person').showModal()}
function render(){if(!data)return;const parts=location.hash.slice(1).split('/');route=routes[parts[0]]?parts[0]:'tree';$('#title').textContent=routes[route][0];$('#description').textContent=routes[route][1];$('#crumb').textContent=route==='research'?'Research Queue':route[0].toUpperCase()+route.slice(1);$('#nav').innerHTML=Object.keys(routes).map((r,i)=>`<a href="#${r}" class="${r===route?'active':''}" ${r===route?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span>${r==='research'?'Research Queue':r[0].toUpperCase()+r.slice(1)}</a>`).join('');
const searching=Boolean($('#search').value),content=$('#content');
if(searching){shown=data.sections.filter(s=>matches(JSON.stringify(s)));content.innerHTML=`<div class="notice">Global search includes canonical content and historical annexes. Legacy results retain their source layer.</div><div class="section-list">${shown.map(s=>section(s)).join('')}</div>`}
else if(['tree','people','timeline'].includes(route)){shown=data.people.filter(p=>matches(JSON.stringify(p)));if(route==='timeline'){let events=shown.filter(p=>!p.living&&/\d{4}/.test(p.dates)).map(p=>({year:+p.dates.match(/\d{4}/)[0],p})).sort((a,b)=>a.year-b.year);content.innerHTML=`<div class="notice">This index orders dated person leads; it does not imply that birth dates or relationships are proved. The complete event chronology is retained in the linked dossier passages.</div><div class="timeline">${events.map(({year,p})=>`<article class="event"><time>${year}</time><h3><button data-person="${p.id}">${esc(p.name)}</button></h3><p>${esc(p.dates)}</p>${badges(p.state)}<p>${esc(p.state)} · ${esc(p.role)}</p></article>`).join('')}</div><h2>Identity and marriage chronology</h2><div class="section-list">${data.sections.filter(s=>!s.legacy&&/^(8\.|8\.1|10\.)/.test(s.title)).map(s=>section(s)).join('')}</div>`}
else if(route==='people')content.innerHTML=`<div class="grid">${shown.map(card).join('')}</div>`;
else{let a=data.people.find(p=>p.name==='Edward Ellery DeVine / DeVeine'),b=data.people.find(p=>p.name==='William John Rahe Sr.');content.innerHTML=`<div class="stats"><div class="stat"><strong>70</strong>Person / identity entries</div><div class="stat"><strong>386</strong>Preserved source tables</div><div class="stat"><strong>9</strong>Legacy source annexes</div><div class="stat"><strong>4</strong>Controlled evidence states</div></div><div class="notice"><b>The central identity question</b><p>Probable same-person hypothesis. The documentary bridge remains UNRESOLVED; these identities remain separate.</p><div class="bridge">${card(a)}<div class="bridge-label">UNRESOLVED<br>probable identity bridge</div>${card(b)}</div></div>${pedigree()}<h2>Family & relationship inventory</h2><p>Grouped by branch. Relationship descriptions are transcribed from Appendix F; proximity does not establish parentage.</p>${[...new Set(shown.map(p=>p.branch))].map(branch=>`<section><div class="branch-heading"><h2>${esc(branch)}</h2><span>${shown.filter(p=>p.branch===branch).length} entries</span></div><div class="grid tree-group">${shown.filter(p=>p.branch===branch).map(card).join('')}</div></section>`).join('')}<h2>Direct-line and relationship registers</h2><div class="section-list">${data.sections.filter(s=>!s.legacy&&/^(3\.|21\.)/.test(s.title)).map(s=>section(s)).join('')}</div>`}}
else{shown=selectedSections();content.innerHTML=(route==='archive'?`<div class="notice"><b>Complete source, explicit precedence</b><p>All ${data.meta.sections} sections and ${data.meta.tables} tables are retained. Public-edition birth redactions are marked in text. Part II is historical evidence, not the current pedigree.</p><a class="action" href="corpus.json" download>Download public dossier JSON ↓</a><a class="action" href="coverage.json" download>Source integrity manifest ↓</a></div>`:'')+`<div class="section-list">${shown.map(s=>section(s,s.id===parts[1])).join('')}</div>`}
$('#status').textContent=`${shown.length} ${['tree','people','timeline'].includes(route)&&!searching?'person entries':'dossier sections'} · ${searching?'All source layers':'Public research edition'}`;if(!shown.length)content.innerHTML='<div class="empty">No matching records. Try another name, source ID, branch, or evidence state.</div>';if(parts[1])requestAnimationFrame(()=>document.getElementById(parts[1])?.scrollIntoView({block:'start'}));}
$('#filters').addEventListener('submit',e=>e.preventDefault());for(const id of ['search','branch','state'])$('#'+id).addEventListener('input',render);$('#filters').addEventListener('reset',()=>setTimeout(render));window.addEventListener('hashchange',()=>{if($('#person').open)$('#person').close();render()});document.addEventListener('click',e=>{const p=e.target.closest('[data-person]');if(p)showPerson(p.dataset.person);if(e.target.closest('[data-dismiss]'))$('#person').close()});$('#close').onclick=()=>$('#person').close();$('#print').onclick=()=>{document.querySelectorAll('details').forEach(d=>d.open=true);window.print()};$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({edition:data.meta.edition,sourceSha256:data.meta.sha256,view:route,records:shown},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`rahe-${route}-public.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
try{const response=await fetch('corpus.json');if(!response.ok)throw Error('Dossier unavailable');data=await response.json();for(const s of data.sections.filter(s=>!s.legacy&&s.title.startsWith('14.')))for(const id of JSON.stringify(s).match(/C\d{3}/g)||[])sourceIndex.set(id,s.id);$('#branch').innerHTML+=[...new Set(data.people.flatMap(p=>p.branch.split('/')))].sort().map(b=>`<option>${esc(b)}</option>`).join('');render()}catch(e){$('#status').textContent='The dossier could not load. Please reload the page or try again later.';console.error(e)}
