import{model,corpus,esc,matches,notice,sectionList,claimCard,sourceCard,taskCard}from'./core.js';
import{renderTraceability}from'./traceability.js';
function canonical(key){const rx={branches:/^(?:4|5|6|7|8|9|10)\./,evidence:/^(?:1\.|3\.|16\.|19\.|20\.|21\.|22\.|Appendix [DFG]|D\.|G\.)/,sources:/^(?:14\.|15\.|Appendix [BE]|E\.)/,research:/^(?:13\.|17\.|18\.|Appendix E|E\.)/,conflicts:/^(?:5\.1|5\.2|8\.|8\.1|12\.|Appendix D|D\.)/,migration:/^(?:11\.|7\.3)/}[key];return corpus.sections.filter(s=>!s.legacy&&rx?.test(s.title));}
export function renderBranches(){const branches=model.branchSummaries.filter(matches);return`<div class="section-title"><div><p class="eyebrow">RESEARCH BRANCHES</p><h2>Branch workspaces</h2></div><span>${branches.length}</span></div><div class="branch-grid">${branches.map(b=>`<article class="branch-card"><h3>${esc(b.name)}</h3><div><span>${b.peopleIds.length} people</span><span>${b.claimIds.length} claims</span><span>${b.taskIds.length} tasks</span></div><button data-branch="${esc(b.name)}">Filter to branch</button></article>`).join('')}</div><h2>Canonical branch dossiers</h2>${sectionList(canonical('branches'))}`;}
export function renderEvidence(){const claims=model.claims.filter(matches),promotion=corpus.sections.find(s=>s.title.startsWith('19.1'));return`${promotion?sectionList([promotion],true):''}<div class="section-title"><div><p class="eyebrow">CLAIM REGISTER</p><h2>Evidence workbench</h2></div><span>${claims.length} of ${model.claims.length}</span></div><div class="claim-grid">${claims.map(claimCard).join('')}</div>${renderTraceability()}<h2>Relationship and completeness controls</h2>${sectionList(canonical('evidence'))}`;}
export function renderSources(){const sources=model.sources.filter(matches);return`<div class="section-title"><div><p class="eyebrow">SOURCE REGISTER</p><h2>Sources and crosswalk</h2></div><span>${sources.length} of ${model.sources.length}</span></div><div class="source-grid">${sources.map(sourceCard).join('')}</div><h2>Canonical source-control sections</h2>${sectionList(canonical('sources'))}`;}
export function renderResearch(){const tasks=model.researchTasks.filter(matches);return`${notice('Queue semantics','Priority and wording are transcribed from section 17. A task is not marked complete unless the controlling dossier is updated.','control')}<div class="section-title"><div><p class="eyebrow">RECORD ACQUISITION</p><h2>Research Queue</h2></div><span>${tasks.length} of ${model.researchTasks.length}</span></div><div class="task-grid">${tasks.map(taskCard).join('')}</div><section><div class="section-title"><h2>Branch acquisition sequences</h2><span>${model.acquisitionSequences.length}</span></div><div class="sequence-list">${model.acquisitionSequences.map(s=>`<article><code>${esc(s.order)}</code><div><b>${esc(s.record)}</b><p>${esc(s.purpose)}</p><small>${esc(s.sequence)}</small></div><a class="deep-link" href="#archive/${s.sourceLocation.section}">Source ↗</a></article>`).join('')}</div></section><section><div class="section-title"><h2>Stop rules</h2><span>${model.stopRules.length}</span></div><div class="gate-grid">${model.stopRules.map(s=>`<article class="gate stop"><b>${esc(s.line)}</b><p>${esc(s.rule)}</p><a class="deep-link" href="#archive/${s.sourceLocation.section}">Source ↗</a></article>`).join('')}</div></section><section><div class="section-title"><h2>Negative-search log</h2><span>${model.negativeSearches.length}</span></div><div class="negative-list">${model.negativeSearches.map(n=>`<article><h3>${esc(n.target)}</h3><p><b>Negative / incomplete:</b> ${esc(n.result)}</p><p><b>Next action:</b> ${esc(n.nextAction)}</p><a class="deep-link" href="#archive/${n.sourceLocation.section}">Source ↗</a></article>`).join('')}</div></section>`;}
export function renderConflicts(){const claims=model.claims.filter(c=>/UNRESOLVED|REJECTED|CONFLICT/i.test(c.state)||/conflict|reject|unresolved/i.test(`${c.claim} ${c.basis}`)).filter(matches);return`${notice('Conflict handling','Unresolved and rejected material stays visible for research control but does not silently enter the active pedigree.','warning')}<div class="claim-grid">${claims.map(claimCard).join('')}</div>${sectionList(canonical('conflicts'))}`;}
export function renderMigration(){return`${notice('Geography discipline','Locations and migration statements are rendered from canonical sections; this release does not infer unstated routes.','control')}${sectionList(canonical('migration'),true)}`;}
export function renderArchive(sectionId){const sections=corpus.sections.filter(matches);return`${notice('Complete public-safe corpus',`${corpus.meta.sections} sections and ${corpus.meta.tables} tables are preserved. Living-person birth redactions are intentional. Part II remains legacy; section 25 is canonical final certification.`,'control')}<div class="archive-actions"><a href="corpus.json" download>Public corpus JSON</a><a href="research-model.json" download>Research model JSON</a><a href="semantic-audit.json" download>Semantic audit JSON</a><a href="redactions.json" download>Redaction ledger</a></div>${sectionList(sections,false,sectionId)}`;}
