import{esc}from'./core.js';
let current=null,bootstrapAvailable=false;
const api=async(body=null)=>{const r=await fetch('/api/auth',{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin',cache:'no-store'}),d=await r.json().catch(()=>({ok:false,error:'Invalid server response.'}));if(!r.ok||!d.ok)throw Error(d.error||`Authentication failed (${r.status})`);return d;};
export const currentUser=()=>current;
export async function refreshAuth(){const d=await api();current=d.user||null;bootstrapAvailable=!!d.bootstrapAvailable;window.dispatchEvent(new CustomEvent('family-auth-changed',{detail:{user:current}}));return current;}
const roleLabel=r=>String(r||'viewer').replace(/^./,x=>x.toUpperCase());
export function renderAuthPanel(){if(current)return`<section class="panel auth-panel"><div class="section-title"><div><p class="eyebrow">FAMILY ACCOUNT · v12.5</p><h2>${esc(current.displayName)}</h2></div><span class="role-badge">${esc(roleLabel(current.role))}</span></div><p class="muted">Signed in as ${esc(current.email)}. Contributions and reviews are attributed to this account.</p><div class="private-actions"><button class="action" data-auth-logout>Sign out</button>${current.role==='admin'?'<button class="action" data-auth-add-user>Add family account</button>':''}</div><div id="auth-admin"></div></section>`;if(bootstrapAvailable)return`<section class="panel auth-panel"><div class="section-title"><div><p class="eyebrow">FIRST ACCOUNT</p><h2>Create family administrator</h2></div><span>One-time setup</span></div><aside class="notice warning"><strong>Bootstrap required</strong><p>Use the existing Family Editor key once to establish the first administrator. After that, normal account sign-in replaces the shared-key workflow.</p></aside><form id="auth-bootstrap" class="form-grid"><label>Name<input name="displayName" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="10" required></label><label>Existing editor key<input name="legacyKey" type="password" required></label><button class="action" type="submit">Create administrator</button></form><div id="auth-status" class="sync-status"></div></section>`;return`<section class="panel auth-panel"><div class="section-title"><div><p class="eyebrow">FAMILY ACCOUNT · v12.5</p><h2>Sign in to contribute</h2></div><span>Viewer access remains public-safe</span></div><form id="auth-login" class="form-grid"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="action" type="submit">Sign in</button></form><div id="auth-status" class="sync-status"></div></section>`;}
function adminForm(){return`<form id="auth-create-user" class="panel inset"><div class="section-title"><div><p class="eyebrow">ADMIN</p><h3>Add family account</h3></div></div><div class="form-grid"><label>Name<input name="displayName" required></label><label>Email<input name="email" type="email" required></label><label>Temporary password<input name="password" type="password" minlength="10" required></label><label>Role<select name="role"><option>viewer</option><option>contributor</option><option>researcher</option><option>editor</option><option>admin</option></select></label></div><div class="private-actions"><button class="action" type="submit">Create account</button><button type="button" data-auth-cancel-user>Cancel</button></div></form>`;}
const status=m=>{const el=document.querySelector('#auth-status');if(el)el.textContent=m;};
function rerender(){window.dispatchEvent(new CustomEvent('family-auth-ui-refresh'));}
export function installAuthHandlers(){if(window.__raheAuthHandlers)return;window.__raheAuthHandlers=true;document.addEventListener('submit',async e=>{try{if(e.target.id==='auth-login'){e.preventDefault();const f=new FormData(e.target);await api({action:'login',email:f.get('email'),password:f.get('password')});await refreshAuth();rerender();return;}if(e.target.id==='auth-bootstrap'){e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json','x-family-editor-key':String(f.get('legacyKey')||'')},body:JSON.stringify({action:'bootstrap',displayName:f.get('displayName'),email:f.get('email'),password:f.get('password')})}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Bootstrap failed.');status('Administrator created. Sign in with the new account.');bootstrapAvailable=false;rerender();return;}if(e.target.id==='auth-create-user'){e.preventDefault();const f=new FormData(e.target),d=await api({action:'create-user',displayName:f.get('displayName'),email:f.get('email'),password:f.get('password'),role:f.get('role')});document.querySelector('#auth-admin').innerHTML=`<p class="sync-status">Created ${esc(d.user.displayName)} as ${esc(d.user.role)}.</p>`;return;}}catch(err){status(err.message);}});document.addEventListener('click',async e=>{try{if(e.target.closest('[data-auth-logout]')){await api({action:'logout'});current=null;await refreshAuth();rerender();return;}if(e.target.closest('[data-auth-add-user]')){const el=document.querySelector('#auth-admin');if(el)el.innerHTML=adminForm();return;}if(e.target.closest('[data-auth-cancel-user]')){const el=document.querySelector('#auth-admin');if(el)el.innerHTML='';return;}}catch(err){status(err.message);}});}
installAuthHandlers();
try{await refreshAuth();}catch{current=null;}
