import{esc,personById}from'./core.js';
import{currentUser}from'./auth.js';

const api='/api/media';
const rank=r=>['viewer','contributor','researcher','editor','admin'].indexOf(String(r||'viewer'));
async function parse(res){const data=await res.json().catch(()=>({ok:false,error:'Invalid server response.'}));if(!res.ok||!data.ok)throw Error(data.error||`Media request failed (${res.status})`);return data;}
async function listMedia(personId){const res=await fetch(`${api}?person=${encodeURIComponent(personId)}`,{credentials:'same-origin',cache:'no-store'});return parse(res);}
async function uploadMedia(form){const data=new FormData(form),res=await fetch(api,{method:'POST',credentials:'same-origin',body:data});return parse(res);}
async function softDelete(id){const res=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete',id})});return parse(res);}
const mediaUrl=id=>`${api}?file=${encodeURIComponent(id)}`;
const card=(m,canDelete)=>`<article class="media-card" data-media-id="${esc(m.id)}"><div class="media-preview">${String(m.mime).startsWith('image/')?`<img src="${mediaUrl(m.id)}" alt="${esc(m.caption||m.title)}">`:`<a class="document-preview" href="${mediaUrl(m.id)}" target="_blank" rel="noopener"><span>PDF</span><b>Open document</b></a>`}</div><div class="media-body"><div class="media-badges"><span>${esc(m.visibility.toUpperCase())}</span><span>${esc(String(m.mime).replace('image/','').replace('application/','').toUpperCase())}</span></div><h3>${esc(m.title)}</h3>${m.caption?`<p>${esc(m.caption)}</p>`:''}<small>${esc(m.contributor||'Family contributor')} · ${esc(String(m.createdAt||'').slice(0,10))}</small>${m.sourceId?`<small>Source reference: ${esc(m.sourceId)}</small>`:''}<small>${esc(m.evidenceAuthority)}</small>${canDelete?`<button class="text-link danger-link" data-media-delete="${esc(m.id)}">Remove from gallery</button>`:''}</div></article>`;

function galleryShell(p){const user=currentUser(),canUpload=!!user&&rank(user.role)>=rank('contributor');return`<section id="person-${esc(p.id)}-media" class="person-media-section"><div class="section-title"><div><p class="eyebrow">PHOTOS & DOCUMENTS</p><h2>Family media</h2></div><span id="media-count">Loading…</span></div><aside class="notice control"><strong>Media remains separate from genealogy evidence</strong><p>Photos and documents can be linked to people and source IDs, but adding media never changes a genealogy evidence state. Media linked to a living person is always private.</p></aside><div id="media-gallery" class="media-grid"><div class="empty compact">Loading media…</div></div>${canUpload?`<details class="media-upload-panel"><summary>Add photo or document</summary><form id="media-upload-form"><input type="hidden" name="personId" value="${esc(p.id)}"><input type="hidden" name="living" value="${p.living?'true':'false'}"><div class="form-grid"><label class="wide">File<input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required></label><label>Title<input name="title" placeholder="Portrait, marriage certificate, census page…"></label><label>Source ID<input name="sourceId" placeholder="C001, W006, etc."></label><label class="wide">Caption<textarea name="caption" rows="3" placeholder="What is shown, where it came from, and who identified it"></textarea></label><label>Visibility<select name="visibility" ${p.living?'disabled':''}><option value="private">Private</option>${p.living?'':'<option value="public">Public</option>'}</select></label></div>${p.living?'<p class="muted">Living-person media is always private regardless of form settings.</p>':''}<button class="action" type="submit">Upload media</button><div id="media-upload-status" class="sync-status" aria-live="polite"></div></form></details>`:`<p class="muted">${user?'Your account is read-only for media. Contributor access or higher is required to upload.':'Sign in with a family account to view private media or contribute photos and documents.'}</p>`}</section>`;}

async function loadGallery(personId){const root=document.querySelector(`#person-${CSS.escape(personId)}-media`);if(!root)return;const gallery=root.querySelector('#media-gallery'),count=root.querySelector('#media-count');try{const data=await listMedia(personId);gallery.innerHTML=data.media.length?data.media.map(m=>card(m,data.canDelete)).join(''):'<div class="empty compact">No photos or documents linked yet.</div>';count.textContent=`${data.media.length} item(s)`;}catch(error){gallery.innerHTML=`<div class="empty compact">${esc(error.message)}</div>`;count.textContent='Unavailable';}}

function mount(){const [kind,id]=location.hash.slice(1).split('/');if(kind!=='person'||!id)return;const p=personById(id),content=document.querySelector('#content');if(!p||!content||content.querySelector(`#person-${CSS.escape(id)}-media`))return;const research=content.querySelector(`#person-${CSS.escape(id)}-research`);if(research)research.insertAdjacentHTML('beforebegin',galleryShell(p));else content.insertAdjacentHTML('beforeend',galleryShell(p));const nav=content.querySelector('.local-nav');if(nav&&!nav.querySelector('[data-scroll$="-media"]')){const b=document.createElement('button');b.type='button';b.dataset.scroll=`person-${id}-media`;b.textContent='Media';nav.appendChild(b);}loadGallery(id);}
function refreshCurrentGallery(){const [kind,id]=location.hash.slice(1).split('/');if(kind==='person'&&id)loadGallery(id);}

document.addEventListener('submit',async e=>{if(e.target.id!=='media-upload-form')return;e.preventDefault();const status=e.target.querySelector('#media-upload-status');status.textContent='Uploading…';try{const data=await uploadMedia(e.target);status.textContent=`Uploaded ${data.media.title}.`;e.target.reset();e.target.elements.personId.value=location.hash.slice(1).split('/')[1]||'';e.target.elements.living.value=personById(e.target.elements.personId.value)?.living?'true':'false';await loadGallery(e.target.elements.personId.value);window.dispatchEvent(new CustomEvent('family-media-changed'));}catch(error){status.textContent=error.message;}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-media-delete]');if(!b)return;if(!confirm('Remove this media item from the active gallery? The blob is retained as a soft-deleted record.'))return;try{await softDelete(b.dataset.mediaDelete);const id=location.hash.slice(1).split('/')[1];if(id)await loadGallery(id);window.dispatchEvent(new CustomEvent('family-media-changed'));}catch(error){alert(error.message);}});
window.addEventListener('hashchange',()=>setTimeout(mount));window.addEventListener('family-edits-changed',()=>setTimeout(mount));window.addEventListener('family-media-changed',()=>setTimeout(refreshCurrentGallery));window.addEventListener('family-auth-changed',()=>setTimeout(()=>{const [kind,id]=location.hash.slice(1).split('/');if(kind==='person'&&id){document.querySelector(`#person-${CSS.escape(id)}-media`)?.remove();mount();}},0));const observer=new MutationObserver(()=>mount());const start=()=>{const content=document.querySelector('#content');if(content)observer.observe(content,{childList:true,subtree:false});mount();};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
