import{esc}from'./core.js';
const KEY='rahe.family.sync.v1',EDITOR_KEY='rahe.family.editor.v1';const now=()=>new Date().toISOString();const blank=()=>({version:1,editorKey:'',contributor:'',lastPulledRevision:null,lastPulledAt:null,lastSubmittedRevision:null});const blankEdits=()=>({version:1,peopleAdded:[],personPatches:{},peopleHidden:[],relationshipsAdded:[],relationshipPatches:{},relationshipsHidden:[],updatedAt:null});
export function loadSyncState(){try{return{...blank(),...(JSON.parse(localStorage.getItem(KEY)||'null')||{})};}catch{return blank();}}
export function saveSyncState(patch){const s={...loadSyncState(),...patch};localStorage.setItem(KEY,JSON.stringify(s));return s;}
const loadEdits=()=>{try{return{...blankEdits(),...(JSON.parse(localStorage.getItem(EDITOR_KEY)||'null')||{})};}catch{return blankEdits();}};
const saveEdits=state=>{localStorage.setItem(EDITOR_KEY,JSON.stringify({...blankEdits(),...state,updatedAt:now()}));window.dispatchEvent(new CustomEvent('family-edits-changed'));};
const headers=()=>{const s=loadSyncState();return{'content-type':'application/json','x-family-editor-key':s.editorKey||''};};
async function parse(res){const data=await res.json().catch(()=>({ok:false,error:'Invalid server response.'}));if(!res.ok||!data.ok)throw Error(data.error||`Sync failed (${res.status})`);return data;}
export async function fetchApprovedRevision(){return parse(await fetch('/api/family-sync?scope=approved',{cache:'no-store'}));}
export async function fetchAllRevisions(){return parse(await fetch('/api/family-sync?scope=all',{headers:headers(),cache:'no-store'}));}
export async function submitCurrentEdits(){const s=loadSyncState();if(!s.editorKey)throw Error('Enter the editor key first.');const data=await parse(await fetch('/api/family-sync',{method:'POST',headers:headers(),body:JSON.stringify({action:'submit',contributor:s.contributor||'Family editor',payload:loadEdits()})}));saveSyncState({lastSubmittedRevision:data.id});return data;}
export async function reviewRevision(id,status){const s=loadSyncState();if(!s.editorKey)throw Error('Enter the editor key first.');return parse(await fetch('/api/family-sync',{method:'POST',headers:headers(),body:JSON.stringify({action:'review',id,status,reviewer:s.contributor||'Family editor'})}));}
export async function pullApprovedRevision(){const data=await fetchApprovedRevision();if(!data.revision)return null;saveEdits(data.revision.payload);saveSyncState({lastPulledRevision:data.revision.id,lastPulledAt:now()});return data.revision;}
const row=r=>`<article class="sync-revision ${esc(r.status)}"><div><b>${esc(r.id)}</b><small>${esc(r.contributor)} · ${esc(String(r.created_at||'').slice(0,19).replace('T',' '))}</small></div><span>${esc(r.status.toUpperCase())}</span>${r.status==='pending'?`<div class="private-actions"><button class="action" data-sync-review="${esc(r.id)}" data-sync-status="approved">Approve</button><button class="action danger" data-sync-review="${esc(r.id)}" data-sync-status="rejected">Reject</button></div>`:''}</article>`;
export function renderSharedSyncPanel(){const s=loadSyncState();return `<section class="panel shared-sync-panel"><div class="section-title"><div><p class="eyebrow">SHARED FAMILY DATA · v12.1</p><h2>Cross-device revision sync</h2></div><span>${s.lastPulledRevision?`Last pulled ${esc(s.lastPulledRevision)}`:'No shared revision pulled yet'}</span></div><aside class="notice control"><strong>Append-only review workflow</strong><p>Local edits are submitted as pending revisions. Nothing overwrites the canonical v10 evidence layer. A revision becomes shared only after explicit approval.</p></aside><div class="form-grid"><label>Contributor name<input data-sync-contributor value="${esc(s.contributor)}" placeholder="Bill, Aimee, etc."></label><label>Editor key<input data-sync-key type="password" value="${esc(s.editorKey)}" autocomplete="off" placeholder="Required to submit/review"></label></div><div class="private-actions"><button class="action" data-sync-save-key>Save connection</button><button class="action" data-sync-submit>Submit current edits for review</button><button class="action" data-sync-pull>Pull latest approved revision</button><button class="action" data-sync-refresh>Refresh revision queue</button></div><p class="muted">The editor key stays only in this browser. Shared revisions are stored separately from canonical evidence.</p><div id="sync-status" class="sync-status" aria-live="polite"></div><div id="sync-revisions" class="sync-revisions"></div></section>`;}
export function renderRevisionRows(revisions=[]){return revisions.length?revisions.map(row).join(''):'<div class="empty compact">No shared revisions yet.</div>';}
export function installSharedSyncHandlers(){if(window.__raheSyncHandlers)return;window.__raheSyncHandlers=true;const status=m=>{const el=document.querySelector('#sync-status');if(el)el.textContent=m;};const refresh=async()=>{status('Loading revisions…');try{const d=await fetchAllRevisions(),el=document.querySelector('#sync-revisions');if(el)el.innerHTML=renderRevisionRows(d.revisions);status(`${d.revisions.length} revision(s) loaded.`);}catch(e){status(e.message);}};document.addEventListener('click',async e=>{try{if(e.target.closest('[data-sync-save-key]')){saveSyncState({editorKey:document.querySelector('[data-sync-key]')?.value||'',contributor:document.querySelector('[data-sync-contributor]')?.value||''});status('Connection saved in this browser.');return;}if(e.target.closest('[data-sync-submit]')){saveSyncState({editorKey:document.querySelector('[data-sync-key]')?.value||'',contributor:document.querySelector('[data-sync-contributor]')?.value||''});const d=await submitCurrentEdits();status(`Submitted ${d.id} for review.`);await refresh();return;}if(e.target.closest('[data-sync-pull]')){const r=await pullApprovedRevision();status(r?`Pulled approved revision ${r.id}.`:'No approved revision exists yet.');return;}if(e.target.closest('[data-sync-refresh]')){await refresh();return;}const b=e.target.closest('[data-sync-review]');if(b){await reviewRevision(b.dataset.syncReview,b.dataset.syncStatus);status(`${b.dataset.syncReview} marked ${b.dataset.syncStatus}.`);await refresh();return;}}catch(err){status(err.message);}});}
