import{esc}from'./core.js';
const KEY='rahe.family.sync.v1',EDITOR_KEY='rahe.family.editor.v1';const now=()=>new Date().toISOString();const blank=()=>({version:1,editorKey:'',contributor:'',lastPulledRevision:null,lastPulledAt:null,lastSubmittedRevision:null});const blankEdits=()=>({version:1,peopleAdded:[],personPatches:{},peopleHidden:[],relationshipsAdded:[],relationshipPatches:{},relationshipsHidden:[],updatedAt:null});
export function loadSyncState(){try{return{...blank(),...(JSON.parse(localStorage.getItem(KEY)||'null')||{})};}catch{return blank();}}
export function saveSyncState(patch){const s={...loadSyncState(),...patch};localStorage.setItem(KEY,JSON.stringify(s));return s;}
const loadEdits=()=>{try{return{...blankEdits(),...(JSON.parse(localStorage.getItem(EDITOR_KEY)||'null')||{})};}catch{return blankEdits();}};
const saveEdits=state=>{localStorage.setItem(EDITOR_KEY,JSON.stringify({...blankEdits(),...state,updatedAt:now()}));window.dispatchEvent(new CustomEvent('family-edits-changed'));};
const headers=()=>{const s=loadSyncState();return{'content-type':'application/json','x-family-editor-key':s.editorKey||''};};
async function parse(res){const data=await res.json().catch(()=>({ok:false,error:'Invalid server response.'}));if(!res.ok||!data.ok)throw Error(data.error||`Sync failed (${res.status})`);return data;}
export async function fetchApprovedRevision(){return parse(await fetch('/api/family-sync?scope=approved',{cache:'no-store'}));}
export async function fetchAllRevisions(){return parse(await fetch('/api/family-sync?scope=all',{headers:headers(),cache:'no-store'}));}
export async function submitCurrentEdits(){const s=loadSyncState();if(!s.editorKey)throw Error('Enter the editor key first.');const data=await parse(await fetch('/api/family-sync',{method:'POST',headers:headers(),body:JSON.stringify({action:'submit',contributor:s.contributor||'Family editor',payload:loadEdits()})}));saveSyncState({lastSubmittedRevision:data.id});return data;}
export async function reviewRevision(id,status){const s=loadSyncState();if(!s.editorKey)throw Error('Enter the editor key first.');return parse(await fetch('/api/family-sync',{method:'POST',headers:headers(),body:JSON.stringify({action:'review',id,status,reviewer:s.contributor||'Family editor'})}));}
export async function pullApprovedRevision(){const data=await fetchApprovedRevision();if(!data.revision)return null;saveEdits(data.revision.payload);saveSyncState({lastPulledRevision:data.revision.id,lastPulledAt:now()});return data.revision;}

const ids=arr=>new Set((arr||[]).map(x=>typeof x==='string'?x:x.id));
const changedKeys=(a={},b={})=>[...new Set([...Object.keys(a||{}),...Object.keys(b||{})])].filter(k=>JSON.stringify(a?.[k])!==JSON.stringify(b?.[k]));
const addedNames=(base,next)=>{const before=ids(base?.peopleAdded),items=(next?.peopleAdded||[]).filter(p=>!before.has(p.id));return items.map(p=>p.name||p.id);};
function revisionDiff(base=blankEdits(),next=blankEdits()){
  const counts={peopleAdded:addedNames(base,next).length,peopleEdited:changedKeys(base.personPatches,next.personPatches).length,peopleHidden:[...(next.peopleHidden||[])].filter(x=>!ids(base.peopleHidden).has(x)).length,relationshipsAdded:(next.relationshipsAdded||[]).filter(r=>!ids(base.relationshipsAdded).has(r.id)).length,relationshipsEdited:changedKeys(base.relationshipPatches,next.relationshipPatches).length,relationshipsHidden:[...(next.relationshipsHidden||[])].filter(x=>!ids(base.relationshipsHidden).has(x)).length};
  const names=addedNames(base,next);return{counts,names,total:Object.values(counts).reduce((a,b)=>a+b,0)};
}
const diffMarkup=(base,r)=>{const d=revisionDiff(base?.payload||blankEdits(),r.payload||blankEdits()),labels=[['peopleAdded','People added'],['peopleEdited','People edited'],['peopleHidden','People hidden'],['relationshipsAdded','Relationships added'],['relationshipsEdited','Relationships edited'],['relationshipsHidden','Relationships hidden']];return`<details><summary>Review changes · ${d.total} change(s)</summary><div class="revision-diff"><div class="revision-diff-grid">${labels.map(([k,l])=>`<article><b>${d.counts[k]}</b><span>${esc(l)}</span></article>`).join('')}</div>${d.names.length?`<div class="revision-diff-list"><b>New people:</b> ${esc(d.names.join(' · '))}</div>`:''}<div class="review-only">Compared with ${base?`preceding approved revision ${esc(base.id)}`:'an empty approved overlay'}. This comparison is review-only; approval remains a separate explicit action.</div></div></details>`;};
const row=(r,base)=>`<article class="sync-revision ${esc(r.status)}"><div><b>${esc(r.id)}</b><small>${esc(r.contributor)} · ${esc(String(r.created_at||'').slice(0,19).replace('T',' '))}</small></div><span>${esc(r.status.toUpperCase())}</span>${r.status==='pending'?`<div class="private-actions"><button class="action" data-sync-review="${esc(r.id)}" data-sync-status="approved">Approve</button><button class="action danger" data-sync-review="${esc(r.id)}" data-sync-status="rejected">Reject</button></div>`:''}${diffMarkup(base,r)}</article>`;
export function renderSharedSyncPanel(){const s=loadSyncState();return `<section class="panel shared-sync-panel"><div class="section-title"><div><p class="eyebrow">SHARED FAMILY DATA · v12.4</p><h2>Cross-device revision sync</h2></div><span>${s.lastPulledRevision?`Last pulled ${esc(s.lastPulledRevision)}`:'No shared revision pulled yet'}</span></div><aside class="notice control"><strong>Append-only review workflow</strong><p>Local edits are submitted as pending revisions. Review now includes a human-readable diff against the preceding approved overlay. Approval remains explicit and nothing overwrites canonical v10 evidence.</p></aside><div class="form-grid"><label>Contributor name<input data-sync-contributor value="${esc(s.contributor)}" placeholder="Bill, Aimee, etc."></label><label>Editor key<input data-sync-key type="password" value="${esc(s.editorKey)}" autocomplete="off" placeholder="Required to submit/review"></label></div><div class="private-actions"><button class="action" data-sync-save-key>Save connection</button><button class="action" data-sync-submit>Submit current edits for review</button><button class="action" data-sync-pull>Pull latest approved revision</button><button class="action" data-sync-refresh>Refresh revision queue</button></div><p class="muted">The editor key stays only in this browser. Shared revisions are stored separately from canonical evidence.</p><div id="sync-status" class="sync-status" aria-live="polite"></div><div id="sync-revisions" class="sync-revisions"></div></section>`;}
export function renderRevisionRows(revisions=[]){if(!revisions.length)return'<div class="empty compact">No shared revisions yet.</div>';return revisions.map((r,i)=>{const older=revisions.slice(i+1).find(x=>x.status==='approved')||null;return row(r,older);}).join('');}
export function installSharedSyncHandlers(){if(window.__raheSyncHandlers)return;window.__raheSyncHandlers=true;const status=m=>{const el=document.querySelector('#sync-status');if(el)el.textContent=m;};const refresh=async()=>{status('Loading revisions…');try{const d=await fetchAllRevisions(),el=document.querySelector('#sync-revisions');if(el)el.innerHTML=renderRevisionRows(d.revisions);status(`${d.revisions.length} revision(s) loaded.`);}catch(e){status(e.message);}};document.addEventListener('click',async e=>{try{if(e.target.closest('[data-sync-save-key]')){saveSyncState({editorKey:document.querySelector('[data-sync-key]')?.value||'',contributor:document.querySelector('[data-sync-contributor]')?.value||''});status('Connection saved in this browser.');return;}if(e.target.closest('[data-sync-submit]')){saveSyncState({editorKey:document.querySelector('[data-sync-key]')?.value||'',contributor:document.querySelector('[data-sync-contributor]')?.value||''});const d=await submitCurrentEdits();status(`Submitted ${d.id} for review.`);await refresh();return;}if(e.target.closest('[data-sync-pull]')){const r=await pullApprovedRevision();status(r?`Pulled approved revision ${r.id}.`:'No approved revision exists yet.');return;}if(e.target.closest('[data-sync-refresh]')){await refresh();return;}const b=e.target.closest('[data-sync-review]');if(b){await reviewRevision(b.dataset.syncReview,b.dataset.syncStatus);status(`${b.dataset.syncReview} marked ${b.dataset.syncStatus}.`);await refresh();return;}}catch(err){status(err.message);}});}
function mount(){if(location.hash.split('/')[0]!=='#editor')return;const content=document.querySelector('#content');if(!content||content.querySelector('.shared-sync-panel'))return;content.insertAdjacentHTML('afterbegin',renderSharedSyncPanel());}
installSharedSyncHandlers();window.addEventListener('hashchange',()=>setTimeout(mount));window.addEventListener('family-edits-changed',()=>setTimeout(mount));const observer=new MutationObserver(()=>mount());const start=()=>{const content=document.querySelector('#content');if(content)observer.observe(content,{childList:true});mount();};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
