const routeKey=()=>location.hash.slice(1).split('/')[0]||'dashboard';
function improveStatus(){const status=document.querySelector('#status');if(!status)return;const text=(status.textContent||'').trim();status.classList.toggle('is-loading',/loading/i.test(text));status.classList.toggle('is-error',/error|failed|unavailable/i.test(text));}
function improveTreeA11y(){document.querySelectorAll('.graph-node[role="button"]').forEach(n=>{n.setAttribute('aria-pressed',n.classList.contains('focused')?'true':'false');});const scroll=document.querySelector('.graph-scroll');if(scroll&&!scroll.dataset.hint){scroll.dataset.hint='1';scroll.setAttribute('aria-describedby','tree-scroll-hint');const hint=document.createElement('p');hint.id='tree-scroll-hint';hint.className='sr-only';hint.textContent='Scroll horizontally and vertically to explore the family tree. Use the focal person controls above to change the family context.';scroll.before(hint);}}
function improveMobileNav(){const nav=document.querySelector('.mobile-family-nav');if(!nav)return;const current=routeKey();nav.querySelectorAll('a[data-mobile-route]').forEach(a=>{const active=a.dataset.mobileRoute===current;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
function improveLongNames(){document.querySelectorAll('.person-card h3,.family-chip b,.recent-people-row b,.branch-journey b').forEach(el=>{if((el.textContent||'').trim().length>30)el.classList.add('long-label');});}
function improveProfileNav(){if(routeKey()!=='person')return;const nav=document.querySelector('.local-nav');if(nav){nav.setAttribute('aria-label','Profile sections');nav.querySelectorAll('button').forEach(b=>{if(!b.title)b.title=b.textContent.trim();});}}
function improveEmptyStates(){document.querySelectorAll('.empty').forEach(el=>{if(!el.querySelector('.empty-mark')){const mark=document.createElement('span');mark.className='empty-mark';mark.setAttribute('aria-hidden','true');mark.textContent='—';el.prepend(mark);}});}
function syncReleaseBadge(){const badge=document.querySelector('.version');if(badge)badge.textContent=document.body.dataset.experience==='research'?'RESEARCH MODE · v12.6.2':'FAMILY VIEW · v12.6.2';}
function apply(){improveStatus();improveTreeA11y();improveMobileNav();improveLongNames();improveProfileNav();improveEmptyStates();syncReleaseBadge();document.body.dataset.qaRelease='12.6.2';}
const observer=new MutationObserver(()=>queueMicrotask(apply));const start=()=>{const content=document.querySelector('#content');if(content)observer.observe(content,{childList:true,subtree:true});apply();};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();window.addEventListener('hashchange',()=>setTimeout(apply));window.addEventListener('click',()=>queueMicrotask(syncReleaseBadge));
