import{displayPeople,personById,esc}from'./core.js';

const api='/api/media';
let cache=null,capabilities={canEdit:false,canUpload:false,authenticated:false};
const mediaUrl=id=>`${api}?file=${encodeURIComponent(id)}`;
const isImage=m=>String(m?.mime||'').startsWith('image/');
const isPdf=m=>String(m?.mime||'')==='application/pdf';
const route=()=>location.hash.slice(1).split('/')[0]||'dashboard';
const personRoute=()=>location.hash.startsWith('#person/')?location.hash.split('/')[1]:'';
async function fetchMedia(force=false){if(cache&&!force)return cache;const r=await fetch(api,{credentials:'same-origin',cache:'no-store'}),d=await r.json().catch(()=>({ok:false,error:'Invalid media response'}));if(!r.ok||!d.ok)throw Error(d.error||`Media request failed (${r.status})`);cache=d.media||[];capabilities={canEdit:!!d.canEdit,canUpload:!!d.canUpload,authenticated:!!d.authenticated};return cache;}
const portraitFor=(id,items=cache||[])=>items.filter(m=>m.visibility==='public'&&isImage(m)&&(m.personIds||[]).includes(id)).sort((a,b)=>Number(Boolean(b.featured))-Number(Boolean(a.featured))||String(b.eventDate||b.createdAt||'').localeCompare(String(a.eventDate||a.createdAt||'')))[0]||null;
const decadeOf=m=>{const y=Number(String(m.eventDate||m.createdAt||'').match(/\b(1[6-9]\d{2}|20\d{2})\b/)?.[1]);return y?`${Math.floor(y/10)*10}s`:'Undated';};
const peopleNames=m=>(m.personIds||[]).map(id=>personById(id)?.name||id).join(', ');
const mediaBranches=m=>[...new Set((m.personIds||[]).map(id=>personById(id)?.branch).filter(Boolean))];

function mediaDialog(){let d=document.querySelector('#media-viewer');if(d)return d;d=document.createElement('dialog');d.id='media-viewer';d.className='media-viewer';d.innerHTML='<form method="dialog"><button class="media-viewer-close" aria-label="Close">×</button></form><div class="media-viewer-content"></div>';document.body.appendChild(d);return d;}
function openMedia(id){const m=(cache||[]).find(x=>x.id===id);if(!m)return;const d=mediaDialog(),c=d.querySelector('.media-viewer-content');c.innerHTML=isImage(m)?`<img src="${mediaUrl(m.id)}" alt="${esc(m.caption||m.title)}"><div class="media-viewer-copy"><span>${esc(m.visibility)}${m.featured?' · featured portrait':''}</span><h2>${esc(m.title||'Family photo')}</h2>${m.caption?`<p>${esc(m.caption)}</p>`:''}<dl>${m.eventDate?`<dt>Date</dt><dd>${esc(m.eventDate)}</dd>`:''}${m.location?`<dt>Place</dt><dd>${esc(m.location)}</dd>`:''}<dt>People</dt><dd>${esc(peopleNames(m)||'Unlinked')}</dd><dt>Branch</dt><dd>${esc(mediaBranches(m).join(', ')||'Unassigned')}</dd>${m.sourceId?`<dt>Source</dt><dd>${esc(m.sourceId)}</dd>`:''}</dl></div>`:`<div class="document-viewer"><span>PDF DOCUMENT</span><h2>${esc(m.title||m.fileName)}</h2>${m.caption?`<p>${esc(m.caption)}</p>`:''}<a class="action" href="${mediaUrl(m.id)}" target="_blank" rel="noopener">Open document</a></div>`;d.showModal();}

function editDialog(){let d=document.querySelector('#media-editor');if(d)return d;d=document.createElement('dialog');d.id='media-editor';d.className='media-editor';const people=displayPeople().slice().sort((a,b)=>a.name.localeCompare(b.name));d.innerHTML=`<form id="media-edit-form"><div class="media-editor-head"><div><p class="eyebrow">MEDIA METADATA</p><h2>Edit archive item</h2></div><button type="button" class="media-editor-close" aria-label="Close">×</button></div><input type="hidden" name="id"><div class="form-grid"><label>Title<input name="title" maxlength="180" required></label><label>Source ID<input name="sourceId" maxlength="40"></label><label>Date / year<input name="eventDate" maxlength="32"></label><label>Location<input name="location" maxlength="240"></label><label class="wide">Caption<textarea name="caption" rows="4" maxlength="2000"></textarea></label><label>Visibility<select name="visibility"><option value="private">Private</option><option value="public">Public</option></select></label><label class="wide">Tagged people<select name="personIds" multiple size="8">${people.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.branch)}</option>`).join('')}</select><small>Privacy is re-evaluated server-side. Living or unresolved people force the item private.</small></label><label class="wide featured-choice"><input name="featured" type="checkbox"> Use as featured portrait when eligible</label></div><div class="media-editor-actions"><button type="button" class="text-link media-editor-cancel">Cancel</button><button class="action" type="submit">Save metadata</button></div><div class="sync-status" data-media-edit-status aria-live="polite"></div></form>`;document.body.appendChild(d);return d;}
function openEdit(id){if(!capabilities.canEdit)return;const m=(cache||[]).find(x=>x.id===id);if(!m)return;const d=editDialog(),f=d.querySelector('#media-edit-form');f.elements.id.value=m.id;f.elements.title.value=m.title||m.fileName||'';f.elements.sourceId.value=m.sourceId||'';f.elements.eventDate.value=m.eventDate||'';f.elements.location.value=m.location||'';f.elements.caption.value=m.caption||'';f.elements.visibility.value=m.visibility==='public'?'public':'private';f.elements.featured.checked=Boolean(m.featured);f.elements.featured.disabled=!isImage(m);for(const o of f.elements.personIds.options)o.selected=(m.personIds||[]).includes(o.value);d.querySelector('[data-media-edit-status]').textContent='';d.showModal();}
async function saveEdit(form){const status=form.querySelector('[data-media-edit-status]'),personIds=[...form.elements.personIds.selectedOptions].map(o=>o.value);if(!personIds.length){status.textContent='Select at least one linked person.';return;}status.textContent='Saving…';const body={action:'update',id:form.elements.id.value,title:form.elements.title.value,caption:form.elements.caption.value,eventDate:form.elements.eventDate.value,location:form.elements.location.value,sourceId:form.elements.sourceId.value,visibility:form.elements.visibility.value,featured:form.elements.featured.checked,personIds};const r=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok||!d.ok)throw Error(d.error||'Could not update media metadata.');cache=null;status.textContent='Saved.';form.closest('dialog')?.close();window.dispatchEvent(new CustomEvent('family-media-changed'));await apply(true);}

function hydratePeople(items){for(const p of displayPeople()){const m=portraitFor(p.id,items);if(!m)continue;document.querySelectorAll(`.person-card [data-person="${CSS.escape(p.id)}"],.family-chip[data-person="${CSS.escape(p.id)}"],.mobile-family-cards [data-person="${CSS.escape(p.id)}"]`).forEach(el=>{if(el.querySelector('.v128-photo'))return;const span=document.createElement('span');span.className='v128-photo';span.style.backgroundImage=`url("${mediaUrl(m.id)}")`;span.setAttribute('aria-hidden','true');el.prepend(span);});}}
function hydrateTree(items){document.querySelectorAll('.graph-node[data-person]').forEach(node=>{const id=node.dataset.person,m=portraitFor(id,items);if(!m||node.querySelector('.v128-svg-photo'))return;const ns='http://www.w3.org/2000/svg',defs=node.ownerSVGElement.querySelector('defs')||node.ownerSVGElement.insertBefore(document.createElementNS(ns,'defs'),node.ownerSVGElement.firstChild),clip=document.createElementNS(ns,'clipPath'),circle=document.createElementNS(ns,'circle'),image=document.createElementNS(ns,'image'),clipId=`portrait-${String(id).replace(/[^a-z0-9]/gi,'-')}`;clip.id=clipId;circle.setAttribute('cx','34');circle.setAttribute('cy','37');circle.setAttribute('r','19');clip.appendChild(circle);defs.appendChild(clip);image.setAttribute('href',mediaUrl(m.id));image.setAttribute('x','14');image.setAttribute('y','17');image.setAttribute('width','40');image.setAttribute('height','40');image.setAttribute('preserveAspectRatio','xMidYMid slice');image.setAttribute('clip-path',`url(#${clipId})`);image.classList.add('v128-svg-photo');node.querySelector('.node-avatar')?.insertAdjacentElement('afterend',image);node.querySelector('.node-initials')?.classList.add('photo-hidden');});}

const mediaTile=m=>`<article class="v128-media-tile ${m.visibility==='private'?'private':''}" data-v128-media="${esc(m.id)}"><button type="button" data-media-open="${esc(m.id)}" aria-label="Open ${esc(m.title||'family media')}">${isImage(m)?`<img src="${mediaUrl(m.id)}" alt="${esc(m.caption||m.title||'Family photo')}" loading="lazy">`:'<span class="v128-doc">PDF</span>'}</button><div><span>${m.featured?'FEATURED · ':''}${esc(m.visibility.toUpperCase())}</span><b>${esc(m.title||m.fileName)}</b><small>${esc([m.eventDate,m.location].filter(Boolean).join(' · ')||decadeOf(m))}</small><small>${esc(peopleNames(m))}</small>${capabilities.canEdit?`<button type="button" class="text-link v128-edit-link" data-media-edit="${esc(m.id)}">Edit metadata & tags</button>`:''}</div></article>`;
function mountDashboardLibrary(items,force=false){if(route()!=='dashboard')return;const content=document.querySelector('#content');if(!content)return;const prior=content.querySelector('.v128-library');if(prior&&!force)return;prior?.remove();const visible=items.filter(m=>m.visibility==='public'||capabilities.authenticated),branches=[...new Set(visible.flatMap(mediaBranches))].sort(),people=displayPeople().filter(p=>visible.some(m=>(m.personIds||[]).includes(p.id))).sort((a,b)=>a.name.localeCompare(b.name));const section=document.createElement('section');section.className='v128-library';section.innerHTML=`<div class="section-title"><div><p class="eyebrow">FAMILY ARCHIVE</p><h2>Photos & documents</h2><p>Browse media by branch, person, decade, or type. Media remains separate from genealogy evidence.</p></div><span>${visible.length} item${visible.length===1?'':'s'}</span></div><div class="v128-media-filters"><label>Type<select data-v128-filter="type"><option value="">All media</option><option value="image">Photos</option><option value="pdf">Documents</option></select></label><label>Decade<select data-v128-filter="decade"><option value="">All decades</option>${[...new Set(visible.map(decadeOf))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Branch<select data-v128-filter="branch"><option value="">All branches</option>${branches.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label><label>Person<select data-v128-filter="person"><option value="">All people</option>${people.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label></div><div class="v128-media-grid">${visible.length?visible.map(mediaTile).join(''):'<div class="empty compact">No family media has been added yet.</div>'}</div>`;content.appendChild(section);}
function filterLibrary(){const root=document.querySelector('.v128-library');if(!root)return;const type=root.querySelector('[data-v128-filter="type"]')?.value||'',decade=root.querySelector('[data-v128-filter="decade"]')?.value||'',branch=root.querySelector('[data-v128-filter="branch"]')?.value||'',person=root.querySelector('[data-v128-filter="person"]')?.value||'';root.querySelectorAll('[data-v128-media]').forEach(tile=>{const m=(cache||[]).find(x=>x.id===tile.dataset.v128Media),ok=!!m&&(!type||(type==='image'?isImage(m):isPdf(m)))&&(!decade||decadeOf(m)===decade)&&(!branch||mediaBranches(m).includes(branch))&&(!person||(m.personIds||[]).includes(person));tile.hidden=!ok;});}

function enrichUpload(){const form=document.querySelector('#media-upload-form');if(!form||form.dataset.v128)return;form.dataset.v128='1';const grid=form.querySelector('.form-grid'),anchorId=personRoute(),anchor=personById(anchorId);const all=displayPeople().slice().sort((a,b)=>a.name.localeCompare(b.name));grid?.insertAdjacentHTML('beforeend',`<label>Date / year<input name="eventDate" placeholder="e.g. 1948-06-12 or circa 1948"></label><label>Location<input name="location" placeholder="Chicago, Illinois"></label><label class="wide">Also tag people<select name="personIds" multiple size="5">${all.filter(p=>p.id!==anchorId).map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.branch)}</option>`).join('')}</select><small>Use ⌘/Ctrl to select multiple family members.</small></label>${!anchor?.living?'<label class="wide featured-choice"><input name="featured" type="checkbox" value="1"> Use this image as the featured portrait for linked people</label>':''}`);const file=form.querySelector('input[type="file"]');if(file){const label=file.closest('label');label?.classList.add('v128-drop-zone');label?.insertAdjacentHTML('afterbegin','<span class="drop-title">Drop a photo or PDF here</span><small>or choose a file · JPEG, PNG, WebP, PDF · max 15 MB</small>');['dragenter','dragover'].forEach(ev=>label?.addEventListener(ev,e=>{e.preventDefault();label.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>label?.addEventListener(ev,e=>{e.preventDefault();label.classList.remove('dragging');if(ev==='drop'&&e.dataTransfer?.files?.length){const dt=new DataTransfer();dt.items.add(e.dataTransfer.files[0]);file.files=dt.files;}}));}}
function enhanceCurrentGallery(items){const root=document.querySelector('.person-media-section');if(!root)return;root.querySelectorAll('.media-card[data-media-id]').forEach(card=>{const id=card.dataset.mediaId,m=items.find(x=>x.id===id);if(!m)return;card.classList.toggle('is-private',m.visibility==='private');if(!card.querySelector('[data-media-open]')){const b=document.createElement('button');b.type='button';b.className='text-link';b.dataset.mediaOpen=id;b.textContent='View details';card.querySelector('.media-body')?.appendChild(b);}if(capabilities.canEdit&&!card.querySelector('[data-media-edit]')){const b=document.createElement('button');b.type='button';b.className='text-link';b.dataset.mediaEdit=id;b.textContent='Edit metadata & tags';card.querySelector('.media-body')?.appendChild(b);}if(capabilities.canEdit&&isImage(m)&&m.visibility==='public'&&!m.featured&&!card.querySelector('[data-media-feature]')){const b=document.createElement('button');b.type='button';b.className='text-link';b.dataset.mediaFeature=id;b.textContent='Use as portrait';card.querySelector('.media-body')?.appendChild(b);}if(m.featured&&!card.querySelector('.featured-media-badge'))card.querySelector('.media-badges')?.insertAdjacentHTML('afterbegin','<span class="featured-media-badge">PORTRAIT</span>');if((m.eventDate||m.location)&&!card.querySelector('.v128-meta'))card.querySelector('.media-body h3')?.insertAdjacentHTML('afterend',`<small class="v128-meta">${esc([m.eventDate,m.location].filter(Boolean).join(' · '))}</small>`);});}
async function setFeatured(id){const m=(cache||[]).find(x=>x.id===id);if(!m)return;const r=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({action:'update',id,personIds:m.personIds,title:m.title,caption:m.caption,eventDate:m.eventDate,location:m.location,sourceId:m.sourceId,visibility:m.visibility,featured:true})}),d=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok||!d.ok)throw Error(d.error||'Could not set portrait.');cache=null;window.dispatchEvent(new CustomEvent('family-media-changed'));await apply(true);}

async function apply(force=false){try{const items=await fetchMedia(force);hydratePeople(items);hydrateTree(items);mountDashboardLibrary(items,force);enrichUpload();enhanceCurrentGallery(items);document.body.dataset.mediaRelease='12.8';}catch(e){console.warn('v12.8 media enhancement unavailable',e);}}
document.addEventListener('click',async e=>{const close=e.target.closest?.('.media-editor-close,.media-editor-cancel');if(close){close.closest('dialog')?.close();return;}const open=e.target.closest?.('[data-media-open]');if(open){openMedia(open.dataset.mediaOpen);return;}const edit=e.target.closest?.('[data-media-edit]');if(edit){openEdit(edit.dataset.mediaEdit);return;}const feature=e.target.closest?.('[data-media-feature]');if(feature){try{feature.disabled=true;feature.textContent='Setting…';await setFeatured(feature.dataset.mediaFeature);}catch(err){alert(err.message);}return;}});
document.addEventListener('submit',async e=>{if(e.target.id!=='media-edit-form')return;e.preventDefault();try{await saveEdit(e.target);}catch(err){e.target.querySelector('[data-media-edit-status]').textContent=err.message;}});
document.addEventListener('change',e=>{if(e.target.closest?.('[data-v128-filter]'))filterLibrary();});
const observer=new MutationObserver(()=>queueMicrotask(()=>apply(false)));const start=()=>{const content=document.querySelector('#content');if(content)observer.observe(content,{childList:true,subtree:true});apply(true);};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();window.addEventListener('hashchange',()=>setTimeout(()=>apply(false)));window.addEventListener('family-auth-changed',()=>{cache=null;document.querySelector('#media-viewer[open]')?.close();document.querySelector('#media-editor[open]')?.close();document.querySelector('.v128-library')?.remove();setTimeout(()=>apply(true));});window.addEventListener('family-media-changed',()=>{cache=null;setTimeout(()=>apply(true));});window.addEventListener('family-edits-changed',()=>setTimeout(()=>apply(false)));
