import{personById,esc}from'./core.js';
const HOME_KEY='rahe.family.home-person.v1',RECENT_KEY='rahe.family.recent-people.v1';
const focusId=()=>new URL(location.href).searchParams.get('focus')||'';
const route=()=>location.hash.slice(1).split('/')[0]||'dashboard';
const recentIds=()=>{try{return(JSON.parse(localStorage.getItem(RECENT_KEY)||'[]')||[]).filter(id=>personById(id)).slice(0,5);}catch{return[]}};
function center(id,instant=false){const node=document.querySelector(`.graph-node[data-person="${CSS.escape(id)}"]`),scroll=document.querySelector('.graph-scroll');if(!node||!scroll)return;const nr=node.getBoundingClientRect(),sr=scroll.getBoundingClientRect();scroll.scrollBy({left:nr.left-sr.left+nr.width/2-sr.width/2,top:nr.top-sr.top+nr.height/2-sr.height/2,behavior:instant?'auto':'smooth'});}
function breadcrumb(){if(route()!=='tree')return;const shell=document.querySelector('.graph-shell');if(!shell)return;let nav=document.querySelector('.v1291-breadcrumb');if(nav)nav.remove();const focus=focusId(),home=localStorage.getItem(HOME_KEY)||'',recent=recentIds().filter(id=>id!==focus);nav=document.createElement('nav');nav.className='v1291-breadcrumb';nav.setAttribute('aria-label','Tree history');nav.innerHTML=`<span>Tree trail</span>${home&&personById(home)?`<button type="button" data-v1291-go="${esc(home)}">Home · ${esc(personById(home).name)}</button>`:''}${recent.map(id=>`<button type="button" data-v1291-go="${esc(id)}">${esc(personById(id).name)}</button>`).join('')}${focus&&personById(focus)?`<b aria-current="page">${esc(personById(focus).name)}</b>`:''}`;shell.insertAdjacentElement('beforebegin',nav);}
function annotateCouples(){document.querySelectorAll('.edge.couple-child').forEach(edge=>edge.classList.add('v1291-couple-child'));document.querySelectorAll('.edge.spouse,.edge.spouse-lead').forEach(edge=>edge.classList.add('v1291-spouse'));}
function improveCollapse(){document.querySelectorAll('.node-collapse[data-collapse-person]').forEach(control=>{const id=control.dataset.collapsePerson,p=personById(id);control.setAttribute('aria-describedby',`collapse-help-${id}`);if(!control.querySelector('title')){const t=document.createElementNS('http://www.w3.org/2000/svg','title');t.textContent=`Show or hide descendants of ${p?.name||id}`;control.prepend(t);}});}
function installMobileHint(){if(route()!=='tree')return;const scroll=document.querySelector('.graph-scroll');if(!scroll||document.querySelector('.v1291-mobile-hint'))return;const hint=document.createElement('div');hint.className='v1291-mobile-hint';hint.textContent='Tap a person to center them; tap again or press Enter to open the profile.';scroll.insertAdjacentElement('beforebegin',hint);}
function syncRelease(){document.body.dataset.treePolishRelease='12.9.1';const edition=document.querySelector('.edition');if(edition)edition.innerHTML=edition.innerHTML.replace(/Family experience v12\.9(?:\.1)?|Family experience v12\.8/g,'Family experience v12.9.1');const version=document.querySelector('.version');if(version)version.textContent=version.textContent.replace(/v12\.\d+(?:\.\d+)?/,'v12.9.1');}
function apply(){syncRelease();if(route()!=='tree')return;breadcrumb();annotateCouples();improveCollapse();installMobileHint();const focus=focusId();if(focus&&matchMedia('(max-width:760px)').matches&&document.body.dataset.lastCentered!==focus){document.body.dataset.lastCentered=focus;requestAnimationFrame(()=>center(focus,true));}}
document.addEventListener('click',e=>{const jump=e.target.closest?.('[data-v1291-go]');if(jump){const u=new URL(location.href);u.searchParams.set('focus',jump.dataset.v1291Go);if(u.searchParams.get('scope')==='all')u.searchParams.set('scope','family');history.replaceState(null,'',u);window.dispatchEvent(new HashChangeEvent('hashchange'));return;}const node=e.target.closest?.('.graph-node[data-person]');if(node&&matchMedia('(max-width:760px)').matches&&!e.target.closest('.node-collapse')){const id=node.dataset.person;if(document.body.dataset.mobileCentered!==id){e.preventDefault();e.stopImmediatePropagation();document.body.dataset.mobileCentered=id;center(id);return;}delete document.body.dataset.mobileCentered;}},true);
window.addEventListener('hashchange',()=>setTimeout(apply));window.addEventListener('family-media-changed',()=>setTimeout(apply));const observer=new MutationObserver(()=>queueMicrotask(apply));const start=()=>{const c=document.querySelector('#content');if(c)observer.observe(c,{childList:true,subtree:true});apply();};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
