import{displayPeople,personById,esc}from'../../core.js';
const HOME_KEY='family.archive.homePerson.v2',RECENT_KEY='family.archive.recentPeople.v2',COLLAPSE_KEY='family.archive.treeCollapsed.v2';
const LEGACY_HOME_KEY='rahe.family.home-person.v1',LEGACY_RECENT_KEYS=['rahe.family.recentPeople.v1','rahe.family.recent-people.v1'],LEGACY_COLLAPSE_KEY='rahe.family.tree.collapsed.v1';
const route=()=>location.hash.slice(1).split('/')[0]||'dashboard';
const currentFocus=()=>new URL(location.href).searchParams.get('focus')||'';
function migrateScalar(key,legacy){try{let value=localStorage.getItem(key);if(value==null){value=localStorage.getItem(legacy);if(value!=null)localStorage.setItem(key,value);}return value||'';}catch{return'';}}
function migrateArray(key,legacyKeys){try{const current=localStorage.getItem(key);if(current!=null)return JSON.parse(current)||[];const merged=[];for(const legacy of legacyKeys){const raw=localStorage.getItem(legacy);if(!raw)continue;for(const value of JSON.parse(raw)||[])if(!merged.includes(value))merged.push(value);}if(merged.length)localStorage.setItem(key,JSON.stringify(merged));return merged;}catch{return[];}}
const readHome=()=>migrateScalar(HOME_KEY,LEGACY_HOME_KEY);
const readRecent=()=>migrateArray(RECENT_KEY,LEGACY_RECENT_KEYS);
const readCollapsed=()=>new Set(migrateArray(COLLAPSE_KEY,[LEGACY_COLLAPSE_KEY]));
const writeCollapsed=set=>localStorage.setItem(COLLAPSE_KEY,JSON.stringify([...set]));
const treeUrl=(id,scope)=>{const u=new URL(location.href);u.searchParams.set('focus',id);u.searchParams.set('scope',scope||u.searchParams.get('scope')||'family');u.hash='tree';return u;};
function navigateTree(id,scope){if(!id)return;history.replaceState(null,'',treeUrl(id,scope));window.dispatchEvent(new HashChangeEvent('hashchange'));}
function centerPerson(id){const node=document.querySelector(`.graph-node[data-person="${CSS.escape(id)}"]`),scroll=document.querySelector('.graph-scroll');if(!node||!scroll)return;const nr=node.getBoundingClientRect(),sr=scroll.getBoundingClientRect();scroll.scrollBy({left:nr.left-sr.left+nr.width/2-sr.width/2,top:nr.top-sr.top+nr.height/2-sr.height/2,behavior:'smooth'});node.focus({preventScroll:true});}
function navigationPanel(){if(route()!=='tree')return;const shell=document.querySelector('.graph-shell');if(!shell||document.querySelector('.v129-tree-memory'))return;const focus=currentFocus(),home=readHome(),recent=readRecent().filter(id=>personById(id)).slice(0,6);const wrap=document.createElement('section');wrap.className='v129-tree-memory';wrap.innerHTML=`<div><span class="eyebrow">TREE NAVIGATION</span><b>${focus?esc(personById(focus)?.name||focus):'Connected family view'}</b></div><div class="v129-memory-actions">${focus?`<button type="button" data-v129-home-set="${esc(focus)}">${home===focus?'Home person ✓':'Set as home person'}</button>`:''}${home&&personById(home)?`<button type="button" data-v129-home-go="${esc(home)}">Go to ${esc(personById(home).name)}</button>`:''}</div>${recent.length?`<div class="v129-recent"><span>Recently viewed</span>${recent.map(id=>`<button type="button" data-v129-recent="${esc(id)}">${esc(personById(id).name)}</button>`).join('')}</div>`:''}`;shell.insertAdjacentElement('beforebegin',wrap);}
function apply(){document.body.dataset.treeRelease='17.2';navigationPanel();}
document.addEventListener('click',e=>{const collapse=e.target.closest?.('[data-collapse-person]');if(collapse){e.preventDefault();e.stopImmediatePropagation();const set=readCollapsed(),id=collapse.dataset.collapsePerson;set.has(id)?set.delete(id):set.add(id);writeCollapsed(set);window.dispatchEvent(new HashChangeEvent('hashchange'));return;}const center=e.target.closest?.('[data-center-person]');if(center){e.preventDefault();centerPerson(center.dataset.centerPerson);return;}const setHome=e.target.closest?.('[data-v129-home-set]');if(setHome){localStorage.setItem(HOME_KEY,setHome.dataset.v129HomeSet);document.querySelector('.v129-tree-memory')?.remove();navigationPanel();return;}const goHome=e.target.closest?.('[data-v129-home-go]');if(goHome){navigateTree(goHome.dataset.v129HomeGo);return;}const recent=e.target.closest?.('[data-v129-recent]');if(recent){navigateTree(recent.dataset.v129Recent);return;}},true);
window.addEventListener('hashchange',()=>setTimeout(apply));window.addEventListener('family-edits-changed',()=>setTimeout(apply));const observer=new MutationObserver(()=>queueMicrotask(apply));const start=()=>{const c=document.querySelector('#content');if(c)observer.observe(c,{childList:true,subtree:false});apply();};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
