import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const ignoredTopLevel=new Set(['.git','.github','docs','e2e','netlify','node_modules','scripts','data','public','dist','exports']);
const requiredBoundaries=['src/app/runtime.js','src/features/family/index.js','src/features/media/index.js','src/features/search/index.js','src/features/tree/index.js','src/features/navigation/model.js','src/features/navigation/runtime.js','src/features/navigation/shell.js','src/features/person/experience.js','src/platform/performance/contracts.js'];
function walk(dir,prefix=''){const out=[];for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const rel=prefix?`${prefix}/${entry.name}`:entry.name;if(!prefix&&ignoredTopLevel.has(entry.name))continue;const abs=path.join(dir,entry.name);if(entry.isDirectory())out.push(...walk(abs,rel));else out.push(rel.replaceAll('\\','/'));}return out;}
const missing=requiredBoundaries.filter(f=>!fs.existsSync(path.join(root,f)));if(missing.length){console.error('Architecture audit failed: permanent ownership boundaries missing.');for(const f of missing)console.error(` - ${f}`);process.exit(1);}
const files=walk(root);const productionJs=files.filter(f=>/\.m?js$/.test(f));const versionPattern=/(?:^|[-_.])v\d+(?:[-_.]\d+)*/i;const versioned=productionJs.filter(f=>versionPattern.test(path.basename(f)));if(versioned.length){console.error('Architecture audit failed: release-numbered production filenames are prohibited.');for(const f of versioned)console.error(` - ${f}`);process.exit(1);}
const runtimeDir=path.join(root,'src/runtime');const flatRuntime=fs.existsSync(runtimeDir)?fs.readdirSync(runtimeDir,{withFileTypes:true}).filter(e=>e.isFile()&&e.name.endsWith('.js')).length:0;if(flatRuntime!==0){console.error(`Architecture audit failed: src/runtime must be empty/retired; found ${flatRuntime} JS files.`);process.exit(1);}
for(const retired of ['src/styles/core.css','src/styles/mobile.css'])if(fs.existsSync(path.join(root,retired))){console.error(`Architecture audit failed: retired CSS sink returned: ${retired}`);process.exit(1);}
const cssFiles=files.filter(f=>f.endsWith('.css'));let legacy=0,important=0;for(const f of cssFiles){const css=fs.readFileSync(path.join(root,f),'utf8');const bytes=Buffer.byteLength(css);if(bytes>80000){console.error(`Architecture audit failed: CSS ownership budget exceeded by ${f}: ${bytes} bytes.`);process.exit(1);}legacy+=(css.match(/\.v\d{2,}[a-z0-9_-]*/gi)||[]).length;important+=(css.match(/!important\b/g)||[]).length;}
if(legacy>1925||important>1145){console.error(`Architecture audit failed: CSS debt increased (legacy selectors=${legacy}/1925, !important=${important}/1145).`);process.exit(1);}
console.log(`Architecture audit passed: zero flat runtime modules; zero release-numbered production filenames; ${cssFiles.length} owned CSS files; legacy selectors=${legacy}; !important=${important}.`);
