import fs from 'node:fs';
const modelPath='public/research-model.json',auditPath='public/semantic-audit.json';
const model=JSON.parse(fs.readFileSync(modelPath,'utf8')),audit=JSON.parse(fs.readFileSync(auditPath,'utf8'));
model.collaborationIdentity={version:'12.5',authority:'ACCOUNT-ATTRIBUTED FAMILY COLLABORATION — NON-CANONICAL',authentication:'Server-side password verification with scrypt-derived hashes and HttpOnly SameSite session cookies.',roles:['viewer','contributor','researcher','editor','admin'],roleRules:{viewer:'Read public-safe family data and approved revisions.',contributor:'Submit family-edit revisions for review.',researcher:'Contributor rights plus research/media workflow participation.',editor:'Review and approve/reject family revisions.',admin:'Editor rights plus create family accounts.'},bootstrapRule:'The existing FAMILY_EDITOR_WRITE_KEY may be used only to bootstrap the first administrator or as a temporary legacy migration credential. It is not the normal collaboration identity.',attributionRule:'Submitted revisions are attributed from the authenticated family account rather than free-text contributor identity.',reviewRule:'Approve/reject requires Editor or Admin role and remains an explicit review action. Optional review notes are stored with the revision.',canonicalRule:'Authentication, roles, attribution, and review workflow never promote or rewrite canonical v10 evidence.'};
model.deploymentProvenance={version:'12.5',artifact:'build-info.json',fields:['release','gitSha','sourceSha256','builtAt'],rule:'Production can be compared directly with repository HEAD using build-info.json; deployment provenance does not alter genealogy data.'};
model.meta.release='12.5';model.meta.version='12.5';model.meta.releaseTitle='Family Accounts + Role-Based Collaboration + Deployment Provenance';
const ids=new Set(['AUD-045','AUD-046','AUD-047','AUD-048']);audit.checks=audit.checks.filter(c=>!ids.has(c.id));audit.checks.push(
{id:'AUD-045',label:'Family collaboration is account-attributed and non-canonical',pass:/NON-CANONICAL/i.test(model.collaborationIdentity.authority)&&/never promote or rewrite canonical v10 evidence/i.test(model.collaborationIdentity.canonicalRule),detail:model.collaborationIdentity.canonicalRule},
{id:'AUD-046',label:'Revision submission and review are role-gated',pass:model.collaborationIdentity.roles.includes('contributor')&&model.collaborationIdentity.roles.includes('editor')&&/Editor or Admin/.test(model.collaborationIdentity.reviewRule),detail:model.collaborationIdentity.reviewRule},
{id:'AUD-047',label:'Shared editor key is reduced to bootstrap or migration',pass:/only to bootstrap the first administrator|temporary legacy migration/i.test(model.collaborationIdentity.bootstrapRule),detail:model.collaborationIdentity.bootstrapRule},
{id:'AUD-048',label:'Production build exposes non-genealogical deployment provenance',pass:model.deploymentProvenance.artifact==='build-info.json'&&/does not alter genealogy data/i.test(model.deploymentProvenance.rule),detail:model.deploymentProvenance.rule}
);audit.version='12.5';audit.pass=audit.checks.every(c=>c.pass);model.audit=audit;fs.writeFileSync(modelPath,JSON.stringify(model,null,2));fs.writeFileSync(auditPath,JSON.stringify(audit,null,2));console.log(JSON.stringify({release:model.meta.release,auditPass:audit.pass,roles:model.collaborationIdentity.roles},null,2));
