import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const model=JSON.parse(fs.readFileSync('public/research-model.json','utf8'));
const audit=JSON.parse(fs.readFileSync('public/semantic-audit.json','utf8'));
const releaseAtLeast1251=()=>{const [a=0,b=0,c=0]=String(model.meta.release).split('.').map(Number);return a>12||(a===12&&(b>5||(b===5&&c>=1)));};
test('v12.5.1 collaboration uses family accounts and roles',()=>{assert(releaseAtLeast1251());assert.equal(model.collaborationIdentity.version,'12.5.1');for(const role of ['viewer','contributor','researcher','editor','admin'])assert(model.collaborationIdentity.roles.includes(role));assert.match(model.collaborationIdentity.authentication,/HttpOnly/i);});
test('editor key is bootstrap or legacy migration only',()=>{assert.match(model.collaborationIdentity.bootstrapRule,/bootstrap the first administrator/i);assert.match(model.collaborationIdentity.attributionRule,/authenticated family account/i);});
test('collaboration uses Netlify Blobs with stale-review protection',()=>{assert.equal(model.sharedFamilyData.storage,'Netlify Blobs');assert.match(model.sharedFamilyData.concurrencyRule,/expectedVersion/i);assert.match(model.collaborationIdentity.storage,/Netlify Blobs/i);});
test('collaboration cannot modify canonical evidence',()=>{assert.match(model.collaborationIdentity.canonicalRule,/never promote or rewrite canonical v10 evidence/i);assert.equal(model.deploymentProvenance.artifact,'build-info.json');});
test('v12.5.1 semantic gates remain passing',()=>{for(const id of ['AUD-045','AUD-046','AUD-047','AUD-048','AUD-049'])assert.equal(audit.checks.find(c=>c.id===id)?.pass,true,id);assert(releaseAtLeast1251());assert.equal(audit.pass,true);});
