import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';
import{buildResearchAutomation}from'../research-automation-v18-5.js';

const model=JSON.parse(fs.readFileSync('public/research-model.json','utf8'));
const people=[...(model.people||[]),...(model.familySupplement?.people||[])];
const relationships=[...(model.relationships||[]),...(model.familySupplement?.relationships||[]),...(model.contextRelationships||[])];
const snapshot=JSON.stringify({model,people,relationships});
const result=buildResearchAutomation({model,people,relationships});

test('v18.5 automation is deterministic, transparent, and read-only',()=>{
  assert.equal(result.version,'18.5.0');
  assert.equal(result.formula,'genealogical importance × evidence weakness × expected value × feasibility');
  assert.match(result.authority,/NO CANONICAL MUTATION AUTHORITY/);
  assert.equal(JSON.stringify({model,people,relationships}),snapshot);
  assert.deepEqual(buildResearchAutomation({model,people,relationships}),result);
  assert.ok(result.tasks.length>0);
  for(const task of result.tasks){
    assert.equal(task.autoGenerated,true);
    assert.match(task.authority,/CANNOT CHANGE CANONICAL EVIDENCE/);
    assert.ok(task.priorityScore>=1&&task.priorityScore<=625);
    for(const factor of Object.values(task.factors))assert.ok(factor>=1&&factor<=5);
  }
});

test('automated prioritization never changes source-controlled evidence state',()=>{
  const beforePeople=new Map(people.map(p=>[p.id,p.state]));
  const beforeRels=new Map(relationships.map(r=>[r.id,r.state]));
  buildResearchAutomation({model,people,relationships});
  for(const p of people)assert.equal(p.state,beforePeople.get(p.id));
  for(const r of relationships)assert.equal(r.state,beforeRels.get(r.id));
});

test('weak parentage and derivative relationship rules remain research tasks only',()=>{
  const weakParent=relationships.find(r=>r.type==='parent-child'&&r.active!==false&&!/SUPPORTED/i.test(String(r.state||''))&&!/REJECTED/i.test(String(r.state||'')));
  if(weakParent){const task=result.tasks.find(t=>t.ruleId==='REL-001'&&t.relationshipId===weakParent.id);assert.ok(task);assert.match(task.detail,/Review documentary support/);}
  const derivative=relationships.find(r=>r.active!==false&&!/REJECTED/i.test(String(r.state||''))&&(/DERIVATIVE/i.test(String(r.state||''))||/derivative/i.test(String(r.provenance||r.role||''))));
  if(derivative)assert.ok(result.tasks.some(t=>t.ruleId==='REL-002'&&t.relationshipId===derivative.id));
});

test('identity-candidate engine never merges identities or exposes living people',()=>{
  const allowed=new Set(['POSSIBLE MATCH','PROBABLE MATCH','INSUFFICIENT EVIDENCE','CONFLICTING EVIDENCE','REJECTED MATCH']);
  const living=new Set(people.filter(p=>p.living).map(p=>p.id));
  for(const candidate of result.identityCandidates){
    assert.ok(allowed.has(candidate.classification));
    assert.match(candidate.authority,/NEVER AUTO-MERGE/);
    assert.notEqual(candidate.personA,candidate.personB);
    assert.equal(living.has(candidate.personA),false);
    assert.equal(living.has(candidate.personB),false);
  }
});

test('DeVine Rahe bridge stays separate unresolved and non-pedigree',()=>{
  const bridge=relationships.find(r=>r.type==='identity-bridge');
  assert.ok(bridge);
  assert.match(String(bridge.state||bridge.evidenceState||''),/UNRESOLVED/i);
  assert.notEqual(bridge.activePedigree,true);
  assert.notEqual(bridge.from,bridge.to);
  const candidate=result.identityCandidates.find(c=>c.relationshipId===bridge.id);
  assert.ok(candidate,'explicit unresolved identity bridge should remain inspectable as a candidate');
  assert.equal(candidate.controllingBridgeState,'UNRESOLVED');
  assert.match(candidate.authority,/NEVER AUTO-MERGE/);
});

test('rejected relationships cannot become active research evidence',()=>{
  const rejected=relationships.filter(r=>/REJECTED/i.test(String(r.state||r.evidenceState||'')));
  assert.ok(rejected.every(r=>r.active===false||r.activePedigree!==true));
  for(const r of rejected)assert.equal(result.tasks.some(t=>t.relationshipId===r.id&&/REL-001|REL-002/.test(t.ruleId)),false);
});
