import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';

const index=fs.readFileSync('index.html','utf8');
const entry=fs.readFileSync('app-entry.js','utf8');
const appRuntime=fs.readFileSync('src/app/runtime.js','utf8');
const baseControls=fs.readFileSync('src/runtime/base-controls.js','utf8');
const experience=fs.readFileSync('src/runtime/experience.js','utf8');
const routeCapabilities=fs.readFileSync('src/runtime/route-capabilities.js','utf8');
const treeController=fs.readFileSync('src/runtime/tree-controller.js','utf8');
const runtime=fs.readFileSync('src/runtime/experience-core.js','utf8');
const navShell=fs.readFileSync('src/runtime/navigation-shell.js','utf8');
const navModel=fs.readFileSync('src/runtime/navigation-model.js','utf8');
const nativeController=fs.readFileSync('src/runtime/native-family-v17-controller.js','utf8');
const nativeRuntime=fs.readFileSync('src/runtime/native-family-v17.js','utf8');
const styleRoot=fs.readFileSync('src/styles/index.css','utf8');
const css=fs.readdirSync('src/styles').filter(f=>f.endsWith('.css')&&f!=='index.css').sort().map(f=>fs.readFileSync('src/styles/'+f,'utf8')).join('\n');
const navCss=css;
const mainRuntime=fs.readFileSync('v11.js','utf8');
const build=fs.readFileSync('scripts/build.mjs','utf8');
const model=JSON.parse(fs.readFileSync('public/research-model.json','utf8'));
const retirement=JSON.parse(fs.readFileSync('public/css-retirement-report.json','utf8'));

function releaseOf(text,pattern){const match=text.match(pattern);assert.ok(match,'release fingerprint missing');return match[1];}
function atLeast(version,major,minor){const [a,b]=version.split('.').map(Number);return a>major||(a===major&&b>=minor);}

test('mobile family navigation remains a persistent touch shell under the current release',()=>{const version=releaseOf(index,/data-ui-release="(\d+\.\d+\.\d+)"/);assert.ok(atLeast(version,17,5));assert.match(index,/id="family-mobile-dock"/);assert.match(index,/href="#dashboard"[^>]*data-dock-route="dashboard"/);assert.match(index,/href="#tree"[^>]*data-dock-route="tree"/);assert.match(index,/href="#families"[^>]*data-dock-route="families"/);assert.match(index,/href="#people"[^>]*data-dock-route="people"/);assert.match(index,/mobile-more/);assert.match(index,/data-dock-search/);assert.match(index,/<a href="#media">Photos<\/a>/);assert.match(index,new RegExp(`app\\.bundle\\.js\\?v=${version.replaceAll('.','\\.')}`));assert.doesNotMatch(entry,/v15-runtime\.js/);assert.match(entry,/src\/app\/runtime\.js/);});

test('browser bootstrap delegates historical layers through canonical app and feature domains',()=>{assert.match(entry,/import '\.\/src\/app\/runtime\.js'/);assert.doesNotMatch(entry,/src\/runtime\/index\.js/);assert.doesNotMatch(entry,/^import '\.\/v\d/m);const expected=['../../v11.js','../runtime/base-controls.js','../../media.js','../../deployment.js','../features/family/index.js','../features/media/index.js','../features/tree/index.js','../features/search/index.js','../../media-page-v13-5.js','../runtime/experience.js'];const actual=[...appRuntime.matchAll(/import ['"]([^'"]+\.js)['"]/g)].map(match=>match[1]);assert.deepEqual(actual,expected);});

test('bootstrap ownership preserves branch-neutral recent-person controls',()=>{assert.match(appRuntime,/import '\.\.\/\.\.\/v11\.js'/);assert.match(appRuntime,/import '\.\.\/runtime\/base-controls\.js'/);assert.match(baseControls,/family\.archive\.recentPeople\.v2/);assert.match(baseControls,/rahe\.family\.recent-people\.v1/);assert.match(baseControls,/data-tree-depth/);assert.match(baseControls,/data-tree-person/);assert.equal(fs.existsSync('v12-3-controls.js'),false);});

test('experience boundary gives native v17 ownership to family routes including Families and Branch',()=>{const expected=['./experience-core','../../v15-family-focus','../../platform-v13-runtime','./page-architecture','./navigation-shell','./performance-contracts','./native-family-v17-controller','./tree-controller','./mobile-ui-ownership','./mobile-experience','./mobile-route-state','./mobile-ui-shell','./mobile-ui-transient','./mobile-ui-phase7'];const actual=[...experience.matchAll(/import ['"]([^'"]+)\.js['"]/g)].map(match=>match[1]);assert.deepEqual(actual,expected);assert.doesNotMatch(experience,/v15-1-runtime\.js/);assert.doesNotMatch(experience,/home-flow\.js/);assert.doesNotMatch(experience,/people-person-experience\.js/);assert.doesNotMatch(experience,/compact-disclosure\.js/);assert.match(experience,/tree-controller\.js/);assert.match(treeController,/v17-6-stability\.js/);assert.match(treeController,/tree-advanced\.js/);assert.match(routeCapabilities,/name:'unified-family-experience'[\s\S]*routes:\['dashboard','tree'\]/);assert.doesNotMatch(experience,/import\('\.\/unified-family-experience\.js'\)/);assert.match(routeCapabilities,/name:'person-experience-v17-3'[\s\S]*routes:\['person'\]/);assert.doesNotMatch(experience,/import\('\.\/person-experience-v17-3\.js'\)/);assert.match(experience,/family-branches-v17-5\.js/);assert.match(nativeController,/nativeRoutes=new Set\(\['dashboard','tree','people','person','families','branch'\]\)/);for(const marker of['data-v17-native="home"','data-v17-native="people"','data-v17-native="person"'])assert.match(nativeRuntime,new RegExp(marker));assert.match(nativeController,/data-v17-native="tree"/);assert.match(nativeController,/renderFamiliesIndex\(\)/);assert.match(nativeController,/renderFamilyBranch\(routeBranchName\(\)\)/);});

test('v15.8 navigation semantics remain the shared family and research shell',()=>{for(const token of["label:'Home'","label:'Tree'","label:'People'","label:'Families'","label:'Photos'","label:'Timeline'","label:'Places & Migration'","label:'Stories'"])assert.match(navModel,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(navShell,/RESEARCH CENTER/);assert.match(navShell,/Search people and branches/);assert.match(navShell,/Search the research archive/);assert.match(navShell,/data-dock-route="families"[^>]*><span>Families<\/span>/);assert.match(navShell,/data-dock-search/);assert.match(navShell,/<a href="#media">Photos<\/a>/);assert.match(navShell,/mobile-more/);assert.match(navCss,/body\[data-v158-context="research"\]/);});

test('legacy Family-only v15.7 v15.9 and v15.10 CSS are retired from the production cascade',()=>{for(const retired of['v15-7.css','v15-9.css','v15-10.css'])assert.doesNotMatch(build,new RegExp(`'${retired.replace('.','\\.')}'`));assert.match(styleRoot,/@import '\.\/core\.css';/);for(const file of['home.css','people.css','person.css'])assert.match(css,new RegExp(`Source: ${file.replace('.','\\.')}`));});

test('historical stylesheet sources are fully retired into semantic ownership',()=>{const retiredFiles=['v11.css','v11-nav.css','v11-2.css','v11-3.css','v11-4.css','v11-6.css','v12.css','v12-2.css','v12-3.css','v12-4.css','v12-5.css','v12-6.css','v12-6-1.css','v12-6-2.css','v12-7.css','v12-8.css','v12-9.css','v12-9-1.css','v13-0.css','dashboard-v13-2.css','media-page-v13-4.css','experience-v13-5.css','v14.css','v15.css','v15-1.css','v15-family-focus.css','platform-v13.css','v15-5.css','v15-6.css','v15-8.css','src/styles/v16.css','src/styles/v16-1.css','src/styles/v16-2.css'];for(const file of retiredFiles)assert.equal(fs.existsSync(file),false,`${file} should be retired`);assert.doesNotMatch(styleRoot,/legacy-compat\.generated\.css/);assert.match(styleRoot,/@import '\.\/core\.css';/);for(const file of['record-ingestion.css','mobile-family.css','responsive.css'])assert.match(css,new RegExp(`Source: ${file.replace('.','\.')}`));assert.match(build,/const legacyStyleSources=\[\]/);assert.match(build,/compatibilityBoundary:null/);assert.match(build,/legacySourceCount:0/);assert.equal(retirement.retiredFiles,33);assert.equal(retirement.migratedSelectorArms,2698);assert.equal(retirement.prunedSelectorArms,19);});

test('mobile dock remains a real touch surface above application content',()=>{assert.match(css,/#family-mobile-dock:not\(\[hidden\]\)/);assert.match(css,/z-index:2147483000!important/);assert.match(css,/pointer-events:auto!important/);assert.match(css,/touch-action:manipulation/);assert.match(css,/--tap-target:48px/);});

test('current experience runtime keeps dock navigation and freshness protection but drops legacy Home enhancers',()=>{const version=releaseOf(runtime,/UI_RELEASE='(\d+\.\d+\.\d+)'/);assert.ok(atLeast(version,17,5));assert.match(runtime,/#family-mobile-dock a\[href\^="#"\]/);assert.match(runtime,/event\.preventDefault\(\);navigate/);assert.match(runtime,/pageshow/);assert.match(runtime,/event\.persisted/);assert.match(runtime,/location\.reload\(\)/);assert.match(runtime,/build-info\.json\?ui-check=/);const [major,minor]=version.split('.').map(Number);assert.match(runtime,new RegExp(`UI_RELEASE='${version.replaceAll('.','\\.')}'`));assert.match(runtime,new RegExp(`STALE_RELOAD_KEY='family\\.archive\\.uiReload\\.v${major}\\.${minor}'`));assert.doesNotMatch(runtime,/enhanceRecentPeople/);assert.doesNotMatch(runtime,/addDashboardPaths/);assert.doesNotMatch(runtime,/enhanceMediaMetric/);});

test('semantic experience consumes the authoritative render lifecycle instead of observing DOM mutations',()=>{assert.doesNotMatch(runtime,/MutationObserver/);assert.match(runtime,/family-view-rendered/);assert.match(mainRuntime,/dispatchEvent\(new CustomEvent\('family-view-rendered'/);});

test('media is owned by the main router and search typing does not rerender the whole app',()=>{assert.match(mainRuntime,/routes\.media=/);assert.match(mainRuntime,/media:\(\)=>'<section data-media-route-host/);assert.match(mainRuntime,/\$\('#search'\)\.addEventListener\('input',\(\)=>syncUrl\(\)\)/);assert.doesNotMatch(mainRuntime,/for\(const id of\['search','branch','state'\]\)\$\('#'\+id\)\.addEventListener\('input',render\)/);});

test('current production build emits a stable JavaScript entry, split chunks, and one stylesheet with current shell stamping',()=>{const shellVersion=releaseOf(index,/data-ui-release="(\d+\.\d+\.\d+)"/),buildVersion=releaseOf(build,/const appVersion='(\d+\.\d+\.\d+)'/);assert.equal(shellVersion,buildVersion);const escaped=shellVersion.replaceAll('.','\\.');assert.match(index,new RegExp(`app\\.bundle\\.js\\?v=${escaped}`));assert.match(index,new RegExp(`styles\\.css\\?v=${escaped}`));assert.match(build,/shell\.replace\(/);assert.match(build,/--splitting/);assert.match(build,/--outdir=dist/);assert.match(build,/--entry-names=app\.bundle/);assert.match(build,/--chunk-names=chunks\/\[name\]-\[hash\]/);assert.match(build,/outfile=dist\/styles\.css/);assert.match(build,/bundler:`esbuild@\$\{ESBUILD_VERSION\}`/);assert.match(build,/browserAssets:\[\.\.\.jsAssets,'styles\.css'\]/);assert.match(build,/splitting:true/);assert.match(build,/criticalRuntime:\['tree-controller','mobile-experience','mobile-ui-shell'\]/);});

test('native Family work cannot alter canonical genealogy semantics',()=>{assert.equal(model.meta.release,'13.0');for(const source of[nativeRuntime,nativeController]){assert.doesNotMatch(source,/\.state\s*=\s*[^=]/);assert.doesNotMatch(source,/relationships?\.push/);assert.doesNotMatch(source,/claims?\.push/);}const bridge=(model.relationships||[]).find(r=>r.type==='identity-bridge');assert.ok(bridge);assert.match(String(bridge.state||''),/UNRESOLVED/i);assert.ok((model.relationships||[]).filter(r=>/REJECTED/i.test(String(r.state||''))).every(r=>r.active===false));});