import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const model=JSON.parse(fs.readFileSync('public/research-model.json','utf8'));
const audit=JSON.parse(fs.readFileSync('public/semantic-audit.json','utf8'));
const ui=fs.readFileSync('src/runtime/family-mode.js','utf8');
const css=fs.readFileSync('v12-6.css','utf8');
const atLeast=x=>{const[a=0,b=0,c=0]=String(x).split('.').map(Number);return a>12||a===12&&(b>6||b===6&&c>=0);};
test('v12.6 defaults to family-first mode',()=>{assert(atLeast(model.meta.release));assert.equal(model.familyExperienceRedesign.defaultMode,'family');assert.match(model.familyExperienceRedesign.homeRule,/default home experience/i);});
test('research workbench remains available',()=>{assert.match(model.familyExperienceRedesign.modes.research,/Full evidence workbench/i);assert.match(ui,/Research mode/);assert.match(ui,/Family view/);});
test('family presentation cannot promote evidence',()=>{assert.match(model.familyExperienceRedesign.canonicalRule,/presentation and navigation only/i);assert.match(model.familyExperienceRedesign.statePresentationRule,/presentation only/i);});
test('mobile retains visual family tree and full tree capability',()=>{assert.match(model.familyExperienceRedesign.treeRule,/mobile retains the visual tree/i);assert.match(css,/\.graph-shell\{display:block!important\}/);assert.match(model.familyExperienceRedesign.treeRule,/Full-tree expert mode remains available/i);});
test('v12.6 semantic gates remain passing',()=>{for(const id of ['AUD-050','AUD-051','AUD-052','AUD-053'])assert.equal(audit.checks.find(c=>c.id===id)?.pass,true,id);assert(atLeast(audit.version));assert.equal(audit.pass,true);});
