import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';
import{buildResearchAutomation}from'../research-automation.js';

const read=path=>fs.readFileSync(path,'utf8');
const json=path=>JSON.parse(read(path));
const model=json('public/research-model.json');
const people=[...(model.people||[]),...(model.familySupplement?.people||[])];
const relationships=[...(model.relationships||[]),...(model.familySupplement?.relationships||[]),...(model.contextRelationships||[])];
const snapshot=JSON.stringify({people,relationships,claims:model.claims,evidenceGaps:model.evidenceGaps});
const result=buildResearchAutomation({model,people,relationships});
const build=read('scripts/build.mjs');
const shell=read('index.html');
const entry=read('app-entry.js');
const experience=read('src/runtime/experience-core.js');
const router=read('v11.js');
const intelligence=read('research-intelligence.js');

test('v18.5 Research Intelligence remains wired under the current synchronized release',()=>{
  assert.match(entry,/APP_VERSION='19\.0\.0'/);
  assert.match(experience,/UI_RELEASE='19\.0\.0'/);
  assert.match(experience,/family\.archive\.uiReload\.v19\.0/);
  assert.match(shell,/data-ui-release="19\.0\.0"/);
  assert.match(shell,/styles\.css\?v=19\.0\.0/);
  assert.match(shell,/app\.bundle\.js\?v=19\.0\.0/);
  assert.match(build,/const appVersion='19\.0\.0'/);
  assert.match(build,/releaseTrain:'v19-family-graph'/);
});

test('research automation remains deterministic advisory output with no canonical mutation',()=>{
  assert.equal(result.authority,'ADVISORY ONLY — HUMAN REVIEW REQUIRED');
  assert.equal(result.formula,'genealogical importance × evidence weakness × expected record value × feasibility');
  assert.deepEqual(buildResearchAutomation({model,people,relationships}),result);
  assert.equal(JSON.stringify({people,relationships,claims:model.claims,evidenceGaps:model.evidenceGaps}),snapshot);
  for(const task of result.tasks){
    assert.equal(task.autoGenerated,true);
    assert.equal(task.authority,'OPERATIONAL REVIEW ONLY — CANNOT CHANGE CANONICAL EVIDENCE');
  }
});

test('identity review excludes living people and active known relatives and never authorizes merge',()=>{
  const living=new Set(people.filter(person=>person.living).map(person=>person.id));
  const pairKey=(a,b)=>[a,b].sort().join('|');
  const knownRelatives=new Set(relationships.filter(rel=>rel.active!==false&&rel.type!=='identity-bridge'&&!/REJECTED/i.test(String(rel.state||rel.evidenceState||''))).map(rel=>pairKey(rel.from,rel.to)));
  for(const candidate of result.identityCandidates){
    assert.equal(candidate.authority,'CANDIDATE REVIEW ONLY — NEVER AUTO-MERGE');
    assert.equal(living.has(candidate.personA),false);
    assert.equal(living.has(candidate.personB),false);
    assert.equal(knownRelatives.has(pairKey(candidate.personA,candidate.personB)),false);
  }
});

test('unresolved identity bridge remains distinct and unresolved',()=>{
  const bridge=relationships.find(rel=>rel.type==='identity-bridge'&&/UNRESOLVED/i.test(String(rel.state||rel.evidenceState||'')));
  assert.ok(bridge,'expected unresolved identity bridge');
  assert.notEqual(bridge.from,bridge.to);
  assert.notEqual(bridge.activePedigree,true);
  const candidate=result.identityCandidates.find(item=>item.relationshipId===bridge.id);
  assert.ok(candidate,'explicit unresolved bridge must remain inspectable');
  assert.equal(candidate.controllingBridgeState,'UNRESOLVED');
  assert.equal(candidate.authority,'CANDIDATE REVIEW ONLY — NEVER AUTO-MERGE');
});

test('Research Intelligence export emits live derived analysis instead of a static descriptor',()=>{
  assert.match(router,/renderResearchIntelligence,analyzeResearchIntelligence/);
  assert.match(router,/k==='intelligence'\)payload\.researchIntelligence=analyzeResearchIntelligence\(\)/);
  assert.doesNotMatch(router,/k==='intelligence'\)payload\.researchIntelligence=model\.researchIntelligence/);
  assert.match(intelligence,/export function analyzeResearchIntelligence\(\)/);
});
